# Tratamiento de datos ligas mayores

En este notebook utilizaremos los datos ya explorados sobre el dataset inicial en la exploración inicial y los trataremos y analizaremos por cada liga mayoritaria por separado, con ellas agrupadas por región y en conjunto.

## Librerias

In [1]:
import pandas as pd
import numpy as np
import scipy as sp
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Carga de datos

In [3]:
S10_dataset = pd.read_csv("C:\\Users\\camil\\OneDrive\\Documentos\\GitHub\\GITHUb\\EDA_DS\\Src\\Data\\S10_Date_sorted")
S10_dataset

,Unnamed: 0,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
0,0,2020-01-03 07:33:00,1241318,KeSPA,NaN,0,1,9.24,2220,SANDBOX Gaming,...,27.0,18.0,0.0,8.2162,2845.0,4432.0,65.0,4723.0,7202.0,118.0
1,1,2020-01-03 09:00:00,1241322,KeSPA,NaN,0,2,9.24,2227,T1,...,42.0,15.0,5.0,8.5406,3657.0,5135.0,93.0,6627.0,8784.0,162.0
2,2,2020-01-03 10:05:00,1241324,KeSPA,NaN,0,3,9.24,1711,T1,...,8.0,1.0,0.0,8.2759,3282.0,4851.0,90.0,5252.0,7933.0,150.0
3,3,2020-01-03 10:57:00,1241328,KeSPA,NaN,0,4,9.24,1999,T1,...,16.0,4.0,9.0,9.4247,3351.0,4671.0,92.0,5190.0,7374.0,144.0
4,4,2020-01-04 05:33:00,1241386,KeSPA,NaN,0,1,9.24,1812,DRX,...,27.0,12.0,4.0,8.9404,3587.0,4809.0,88.0,5114.0,7078.0,134.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5144,5144,2020-08-18 20:25:00,1310259,EM,NaN,0,1,10.16,2075,Racoon,...,12.0,8.0,4.0,6.9976,3613.0,4564.0,83.0,5159.0,6917.0,127.0
5145,5145,2020-08-18 20:27:00,1310260,EM,NaN,0,1,10.16,2095,SINNERS Esports,...,8.0,0.0,4.0,4.4105,2509.0,3346.0,49.0,4212.0,4791.0,72.0
5146,5146,2020-08-18 20:53:00,1310262,EM,NaN,0,1,10.16,2879,Team GamerLegion,...,10.0,10.0,0.0,7.0441,2995.0,4173.0,54.0,4536.0,6535.0,93.0
5147,5147,2020-08-18 20:56:00,1320317,EM,NaN,0,1,10.16,1874,G2 Arctic,...,1.0,1.0,0.0,6.1473,3177.0,4291.0,57.0,5139.0,7260.0,109.0
5148,5148,2020-08-18 21:27:00,1310264,EM,NaN,0,1,10.16,1808,Intrepid Fox Gaming,...,0.0,0.0,0.0,7.6991,3027.0,4252.0,74.0,4764.0,7047.0,124.0

In [4]:
del S10_dataset["Unnamed: 0"]
S10_dataset

,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,t1_ban1,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
0,2020-01-03 07:33:00,1241318,KeSPA,NaN,0,1,9.24,2220,SANDBOX Gaming,LeBlanc,...,27.0,18.0,0.0,8.2162,2845.0,4432.0,65.0,4723.0,7202.0,118.0
1,2020-01-03 09:00:00,1241322,KeSPA,NaN,0,2,9.24,2227,T1,Syndra,...,42.0,15.0,5.0,8.5406,3657.0,5135.0,93.0,6627.0,8784.0,162.0
2,2020-01-03 10:05:00,1241324,KeSPA,NaN,0,3,9.24,1711,T1,LeBlanc,...,8.0,1.0,0.0,8.2759,3282.0,4851.0,90.0,5252.0,7933.0,150.0
3,2020-01-03 10:57:00,1241328,KeSPA,NaN,0,4,9.24,1999,T1,Rumble,...,16.0,4.0,9.0,9.4247,3351.0,4671.0,92.0,5190.0,7374.0,144.0
4,2020-01-04 05:33:00,1241386,KeSPA,NaN,0,1,9.24,1812,DRX,Qiyana,...,27.0,12.0,4.0,8.9404,3587.0,4809.0,88.0,5114.0,7078.0,134.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5144,2020-08-18 20:25:00,1310259,EM,NaN,0,1,10.16,2075,Racoon,Caitlyn,...,12.0,8.0,4.0,6.9976,3613.0,4564.0,83.0,5159.0,6917.0,127.0
5145,2020-08-18 20:27:00,1310260,EM,NaN,0,1,10.16,2095,SINNERS Esports,Shen,...,8.0,0.0,4.0,4.4105,2509.0,3346.0,49.0,4212.0,4791.0,72.0
5146,2020-08-18 20:53:00,1310262,EM,NaN,0,1,10.16,2879,Team GamerLegion,Nidalee,...,10.0,10.0,0.0,7.0441,2995.0,4173.0,54.0,4536.0,6535.0,93.0
5147,2020-08-18 20:56:00,1320317,EM,NaN,0,1,10.16,1874,G2 Arctic,Cho'Gath,...,1.0,1.0,0.0,6.1473,3177.0,4291.0,57.0,5139.0,7260.0,109.0
5148,2020-08-18 21:27:00,1310264,EM,NaN,0,1,10.16,1808,Intrepid Fox Gaming,Akali,...,0.0,0.0,0.0,7.6991,3027.0,4252.0,74.0,4764.0,7047.0,124.0

## Tratamiento de datos

### Por liga

#### LPL

In [5]:
lpl = S10_dataset[S10_dataset["league"] == "LPL"]

In [6]:
lpl.head()

,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,t1_ban1,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
10,2020-01-13 09:22:00,5655-7249,LPL,Spring,0,1,10.1,2640,Invictus Gaming,Pantheon,...,8.0,0.0,0.0,3.5682,2898.0,4137.0,59.0,4738.0,6159.0,84.0
11,2020-01-13 10:37:00,5655-7250,LPL,Spring,0,2,10.1,1814,Invictus Gaming,Pantheon,...,24.0,12.0,0.0,7.6075,3492.0,4698.0,63.0,6404.0,8095.0,101.0
12,2020-01-13 11:26:00,5656-7252,LPL,Spring,0,1,10.1,2283,LGD Gaming,Pantheon,...,14.0,10.0,0.0,6.7806,2963.0,4413.0,71.0,4100.0,5983.0,94.0
13,2020-01-13 11:31:00,5655-7251,LPL,Spring,0,3,10.1,1943,Invictus Gaming,Pantheon,...,21.0,17.0,1.0,8.1215,3375.0,5040.0,84.0,5463.0,7782.0,131.0
14,2020-01-13 12:29:00,5656-7253,LPL,Spring,0,2,10.1,1517,LNG Esports,Qiyana,...,8.0,8.0,0.0,8.4245,3070.0,4198.0,65.0,5022.0,7376.0,125.0

In [7]:
lpl.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 711 entries, 10 to 5074
Data columns (total 408 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    date                          711 non-null    object
 1    gameId                        711 non-null    object
 2    league                        711 non-null    object
 3    split                         711 non-null    object
 4    playoffs                      711 non-null    int64
 5    game                          711 non-null    int64
 6    patch                         711 non-null    float64
 7    gamelength                    711 non-null    int64
 8    t1_playerid                   711 non-null    object
 9    t1_ban1                       702 non-null    object
 10   t1_ban2                       702 non-null    object
 11   t1_ban3                       702 non-null    object
 12   t1_ban4                       701 non-null    object
 13   t1_ban5                       701 non-null    object
 14   t1_result                     711 non-null    int64
 15   t1_firstblood                 710 non-null    float64
 16   t1_firstdragon                692 non-null    float64
 17   t1_dragons                    711 non-null    int64
 18   t1_elementaldrakes            675 non-null    float64
 19   t1_infernals                  675 non-null    float64
 20   t1_mountains                  675 non-null    float64
 21   t1_clouds                     675 non-null    float64
 22   t1_oceans                     675 non-null    float64
 23   t1_elders                     692 non-null    float64
 24   t1_firstherald                692 non-null    float64
 25   t1_heralds                    671 non-null    float64
 26   t1_firstbaron                 629 non-null    float64
 27   t1_barons                     711 non-null    int64
 28   t1_firsttower                 710 non-null    float64
 29   t1_towers                     711 non-null    int64
 30   t1_firstmidtower              692 non-null    float64
 31   t1_firsttothreetowers         692 non-null    float64
 32   t1_inhibitors                 692 non-null    float64
 33   t2_playerid                   711 non-null    object
 34   t2_ban1                       702 non-null    object
 35   t2_ban2                       702 non-null    object
 36   t2_ban3                       700 non-null    object
 37   t2_ban4                       701 non-null    object
 38   t2_ban5                       700 non-null    object
 39   t2_result                     711 non-null    int64
 40   t2_firstblood                 710 non-null    float64
 41   t2_firstdragon                692 non-null    float64
 42   t2_dragons                    711 non-null    int64
 43   t2_elementaldrakes            675 non-null    float64
 44   t2_infernals                  675 non-null    float64
 45   t2_mountains                  675 non-null    float64
 46   t2_clouds                     675 non-null    float64
 47   t2_oceans                     675 non-null    float64
 48   t2_elders                     692 non-null    float64
 49   t2_firstherald                692 non-null    float64
 50   t2_heralds                    671 non-null    float64
 51   t2_firstbaron                 629 non-null    float64
 52   t2_barons                     711 non-null    int64
 53   t2_firsttower                 710 non-null    float64
 54   t2_towers                     711 non-null    int64
 55   t2_firstmidtower              692 non-null    float64
 56   t2_firsttothreetowers         692 non-null    float64
 57   t2_inhibitors                 692 non-null    float64
 58   t1p1_position                 711 non-null    object
 59   t1p1_player                   711 non-null    object
 60   t1p1_team                     711 non-null    object
 61   t1p1_champion                 711 non-null    object
 62   t1p1_kills                    711 non-null    int64
 63   t1p1_deaths                   711 non-null    int64
 64   t1p1_assists                  711 non-null    int64
 65   t1p1_firstblood               671 non-null    float64
 66   t1p1_firstbloodkill           710 non-null    float64
 67   t1p1_firstbloodassist         692 non-null    float64
 68   t1p1_firstbloodvictim         692 non-null    float64
 69   t1p1_damagetochampions        710 non-null    float64
 70   t1p1_dpm                      710 non-null    float64
 71   t1p1_wardsplaced              710 non-null    float64
 72   t1p1_wpm                      710 non-null    float64
 73   t1p1_wardskilled              710 non-null    float64
 74   t1p1_wcpm                     710 non-null    float64
 75   t1p1_controlwardsbought       710 non-null    float64
 76   t1p1_visionscore              671 non-null    float64
 77   t1p1_vspm                     671 non-null    float64
 78   t1p1_totalgold                711 non-null    int64
 79   t1p1_earnedgold               711 non-null    int64
 80   t1p1_earned gpm               711 non-null    float64
 81   t1p1_goldspent                692 non-null    float64
 82   t1p1_minionkills              710 non-null    float64
 83   t1p1_monsterkills             710 non-null    float64
 84   t1p1_monsterkillsownjungle    710 non-null    float64
 85   t1p1_monsterkillsenemyjungle  710 non-null    float64
 86   t1p1_cspm                     711 non-null    float64
 87   t1p1_goldat10                 692 non-null    float64
 88   t1p1pat10                     692 non-null    float64
 89   t1p1_csat10                   692 non-null    float64
 90   t1p1_goldat15                 692 non-null    float64
 91   t1p1pat15                     692 non-null    float64
 92   t1p1_csat15                   692 non-null    float64
 93   t1p2_position                 711 non-null    object
 94   t1p2_player                   711 non-null    object
 95   t1p2_team                     711 non-null    object
 96   t1p2_champion                 711 non-null    object
 97   t1p2_kills                    711 non-null    int64
 98   t1p2_deaths                   711 non-null    int64
 99   t1p2_assists                  711 non-null    int64
 100  t1p2_firstblood               671 non-null    float64
 101  t1p2_firstbloodkill           710 non-null    float64
 102  t1p2_firstbloodassist         692 non-null    float64
 103  t1p2_firstbloodvictim         692 non-null    float64
 104  t1p2_damagetochampions        710 non-null    float64
 105  t1p2_dpm                      710 non-null    float64
 106  t1p2_wardsplaced              710 non-null    float64
 107  t1p2_wpm                      710 non-null    float64
 108  t1p2_wardskilled              710 non-null    float64
 109  t1p2_wcpm                     710 non-null    float64
 110  t1p2_controlwardsbought       710 non-null    float64
 111  t1p2_visionscore              671 non-null    float64
 112  t1p2_vspm                     671 non-null    float64
 113  t1p2_totalgold                711 non-null    int64
 114  t1p2_earnedgold               711 non-null    int64
 115  t1p2_earned gpm               711 non-null    float64
 116  t1p2_goldspent                692 non-null    float64
 117  t1p2_minionkills              710 non-null    float64
 118  t1p2_monsterkills             710 non-null    float64
 119  t1p2_monsterkillsownjungle    710 non-null    float64
 120  t1p2_monsterkillsenemyjungle  710 non-null    float64
 121  t1p2_cspm                     711 non-null    float64
 122  t1p2_goldat10                 692 non-null    float64
 123  t1p2pat10                     692 non-null    float64
 124  t1p2_csat10                   692 non-null    float64
 125  t1p2_goldat15                 692 non-null    float64
 126  t1p2pat15                     692 non-null    float64
 127  t1p2_csat15                   692 non-null    float64
 128  t1p3_position                 711 non-null    object
 129  t1p3_player                   711 non-null    object
 130  t1p3_team                     711 non-null    object
 131  t1p3_champion                 711 non-null    object
 132  t1p3_kills                    711 non-null    int64
 133  t1p3_deaths                   711 non-null    int64
 134  t1p3_assists                  711 non-null    int64
 135  t1p3_firstblood               671 non-null    float64
 136  t1p3_firstbloodkill           710 non-null    float64
 137  t1p3_firstbloodassist         692 non-null    float64
 138  t1p3_firstbloodvictim         692 non-null    float64
 139  t1p3_damagetochampions        710 non-null    float64
 140  t1p3_dpm                      710 non-null    float64
 141  t1p3_wardsplaced              710 non-null    float64
 142  t1p3_wpm                      710 non-null    float64
 143  t1p3_wardskilled              710 non-null    float64
 144  t1p3_wcpm                     710 non-null    float64
 145  t1p3_controlwardsbought       710 non-null    float64
 146  t1p3_visionscore              671 non-null    float64
 147  t1p3_vspm                     671 non-null    float64
 148  t1p3_totalgold                711 non-null    int64
 149  t1p3_earnedgold               711 non-null    int64
 150  t1p3_earned gpm               711 non-null    float64
 151  t1p3_goldspent                692 non-null    float64
 152  t1p3_minionkills              710 non-null    float64
 153  t1p3_monsterkills             710 non-null    float64
 154  t1p3_monsterkillsownjungle    710 non-null    float64
 155  t1p3_monsterkillsenemyjungle  710 non-null    float64
 156  t1p3_cspm                     711 non-null    float64
 157  t1p3_goldat10                 692 non-null    float64
 158  t1p3pat10                     692 non-null    float64
 159  t1p3_csat10                   692 non-null    float64
 160  t1p3_goldat15                 692 non-null    float64
 161  t1p3pat15                     692 non-null    float64
 162  t1p3_csat15                   692 non-null    float64
 163  t1p4_position                 711 non-null    object
 164  t1p4_player                   711 non-null    object
 165  t1p4_team                     711 non-null    object
 166  t1p4_champion                 711 non-null    object
 167  t1p4_kills                    711 non-null    int64
 168  t1p4_deaths                   711 non-null    int64
 169  t1p4_assists                  711 non-null    int64
 170  t1p4_firstblood               671 non-null    float64
 171  t1p4_firstbloodkill           710 non-null    float64
 172  t1p4_firstbloodassist         692 non-null    float64
 173  t1p4_firstbloodvictim         692 non-null    float64
 174  t1p4_damagetochampions        710 non-null    float64
 175  t1p4_dpm                      710 non-null    float64
 176  t1p4_wardsplaced              710 non-null    float64
 177  t1p4_wpm                      710 non-null    float64
 178  t1p4_wardskilled              710 non-null    float64
 179  t1p4_wcpm                     710 non-null    float64
 180  t1p4_controlwardsbought       710 non-null    float64
 181  t1p4_visionscore              671 non-null    float64
 182  t1p4_vspm                     671 non-null    float64
 183  t1p4_totalgold                711 non-null    int64
 184  t1p4_earnedgold               711 non-null    int64
 185  t1p4_earned gpm               711 non-null    float64
 186  t1p4_goldspent                692 non-null    float64
 187  t1p4_minionkills              710 non-null    float64
 188  t1p4_monsterkills             710 non-null    float64
 189  t1p4_monsterkillsownjungle    710 non-null    float64
 190  t1p4_monsterkillsenemyjungle  710 non-null    float64
 191  t1p4_cspm                     711 non-null    float64
 192  t1p4_goldat10                 692 non-null    float64
 193  t1p4pat10                     692 non-null    float64
 194  t1p4_csat10                   692 non-null    float64
 195  t1p4_goldat15                 692 non-null    float64
 196  t1p4pat15                     692 non-null    float64
 197  t1p4_csat15                   692 non-null    float64
 198  t1p5_position                 711 non-null    object
 199  t1p5_player                   711 non-null    object
 200  t1p5_team                     711 non-null    object
 201  t1p5_champion                 711 non-null    object
 202  t1p5_kills                    711 non-null    int64
 203  t1p5_deaths                   711 non-null    int64
 204  t1p5_assists                  711 non-null    int64
 205  t1p5_firstblood               671 non-null    float64
 206  t1p5_firstbloodkill           710 non-null    float64
 207  t1p5_firstbloodassist         692 non-null    float64
 208  t1p5_firstbloodvictim         692 non-null    float64
 209  t1p5_damagetochampions        710 non-null    float64
 210  t1p5_dpm                      710 non-null    float64
 211  t1p5_wardsplaced              710 non-null    float64
 212  t1p5_wpm                      710 non-null    float64
 213  t1p5_wardskilled              710 non-null    float64
 214  t1p5_wcpm                     710 non-null    float64
 215  t1p5_controlwardsbought       710 non-null    float64
 216  t1p5_visionscore              671 non-null    float64
 217  t1p5_vspm                     671 non-null    float64
 218  t1p5_totalgold                711 non-null    int64
 219  t1p5_earnedgold               711 non-null    int64
 220  t1p5_earned gpm               711 non-null    float64
 221  t1p5_goldspent                692 non-null    float64
 222  t1p5_minionkills              710 non-null    float64
 223  t1p5_monsterkills             710 non-null    float64
 224  t1p5_monsterkillsownjungle    710 non-null    float64
 225  t1p5_monsterkillsenemyjungle  710 non-null    float64
 226  t1p5_cspm                     711 non-null    float64
 227  t1p5_goldat10                 692 non-null    float64
 228  t1p5pat10                     692 non-null    float64
 229  t1p5_csat10                   692 non-null    float64
 230  t1p5_goldat15                 692 non-null    float64
 231  t1p5pat15                     692 non-null    float64
 232  t1p5_csat15                   692 non-null    float64
 233  t2p1_position                 711 non-null    object
 234  t2p1_player                   711 non-null    object
 235  t2p1_team                     711 non-null    object
 236  t2p1_champion                 711 non-null    object
 237  t2p1_kills                    711 non-null    int64
 238  t2p1_deaths                   711 non-null    int64
 239  t2p1_assists                  711 non-null    int64
 240  t2p1_firstblood               671 non-null    float64
 241  t2p1_firstbloodkill           710 non-null    float64
 242  t2p1_firstbloodassist         692 non-null    float64
 243  t2p1_firstbloodvictim         692 non-null    float64
 244  t2p1_damagetochampions        710 non-null    float64
 245  t2p1_dpm                      710 non-null    float64
 246  t2p1_wardsplaced              710 non-null    float64
 247  t2p1_wpm                      710 non-null    float64
 248  t2p1_wardskilled              710 non-null    float64
 249  t2p1_wcpm                     710 non-null    float64
 250  t2p1_controlwardsbought       710 non-null    float64
 251  t2p1_visionscore              671 non-null    float64
 252  t2p1_vspm                     671 non-null    float64
 253  t2p1_totalgold                711 non-null    int64
 254  t2p1_earnedgold               711 non-null    int64
 255  t2p1_earned gpm               711 non-null    float64
 256  t2p1_goldspent                692 non-null    float64
 257  t2p1_minionkills              710 non-null    float64
 258  t2p1_monsterkills             710 non-null    float64
 259  t2p1_monsterkillsownjungle    710 non-null    float64
 260  t2p1_monsterkillsenemyjungle  710 non-null    float64
 261  t2p1_cspm                     711 non-null    float64
 262  t2p1_goldat10                 692 non-null    float64
 263  t2p1pat10                     692 non-null    float64
 264  t2p1_csat10                   692 non-null    float64
 265  t2p1_goldat15                 692 non-null    float64
 266  t2p1pat15                     692 non-null    float64
 267  t2p1_csat15                   692 non-null    float64
 268  t2p2_position                 711 non-null    object
 269  t2p2_player                   711 non-null    object
 270  t2p2_team                     711 non-null    object
 271  t2p2_champion                 711 non-null    object
 272  t2p2_kills                    711 non-null    int64
 273  t2p2_deaths                   711 non-null    int64
 274  t2p2_assists                  711 non-null    int64
 275  t2p2_firstblood               671 non-null    float64
 276  t2p2_firstbloodkill           710 non-null    float64
 277  t2p2_firstbloodassist         692 non-null    float64
 278  t2p2_firstbloodvictim         692 non-null    float64
 279  t2p2_damagetochampions        710 non-null    float64
 280  t2p2_dpm                      710 non-null    float64
 281  t2p2_wardsplaced              710 non-null    float64
 282  t2p2_wpm                      710 non-null    float64
 283  t2p2_wardskilled              710 non-null    float64
 284  t2p2_wcpm                     710 non-null    float64
 285  t2p2_controlwardsbought       710 non-null    float64
 286  t2p2_visionscore              671 non-null    float64
 287  t2p2_vspm                     671 non-null    float64
 288  t2p2_totalgold                711 non-null    int64
 289  t2p2_earnedgold               711 non-null    int64
 290  t2p2_earned gpm               711 non-null    float64
 291  t2p2_goldspent                692 non-null    float64
 292  t2p2_minionkills              710 non-null    float64
 293  t2p2_monsterkills             710 non-null    float64
 294  t2p2_monsterkillsownjungle    710 non-null    float64
 295  t2p2_monsterkillsenemyjungle  710 non-null    float64
 296  t2p2_cspm                     711 non-null    float64
 297  t2p2_goldat10                 692 non-null    float64
 298  t2p2pat10                     692 non-null    float64
 299  t2p2_csat10                   692 non-null    float64
 300  t2p2_goldat15                 692 non-null    float64
 301  t2p2pat15                     692 non-null    float64
 302  t2p2_csat15                   692 non-null    float64
 303  t2p3_position                 711 non-null    object
 304  t2p3_player                   711 non-null    object
 305  t2p3_team                     711 non-null    object
 306  t2p3_champion                 711 non-null    object
 307  t2p3_kills                    711 non-null    int64
 308  t2p3_deaths                   711 non-null    int64
 309  t2p3_assists                  711 non-null    int64
 310  t2p3_firstblood               671 non-null    float64
 311  t2p3_firstbloodkill           710 non-null    float64
 312  t2p3_firstbloodassist         692 non-null    float64
 313  t2p3_firstbloodvictim         692 non-null    float64
 314  t2p3_damagetochampions        710 non-null    float64
 315  t2p3_dpm                      710 non-null    float64
 316  t2p3_wardsplaced              710 non-null    float64
 317  t2p3_wpm                      710 non-null    float64
 318  t2p3_wardskilled              710 non-null    float64
 319  t2p3_wcpm                     710 non-null    float64
 320  t2p3_controlwardsbought       710 non-null    float64
 321  t2p3_visionscore              671 non-null    float64
 322  t2p3_vspm                     671 non-null    float64
 323  t2p3_totalgold                711 non-null    int64
 324  t2p3_earnedgold               711 non-null    int64
 325  t2p3_earned gpm               711 non-null    float64
 326  t2p3_goldspent                692 non-null    float64
 327  t2p3_minionkills              710 non-null    float64
 328  t2p3_monsterkills             710 non-null    float64
 329  t2p3_monsterkillsownjungle    710 non-null    float64
 330  t2p3_monsterkillsenemyjungle  710 non-null    float64
 331  t2p3_cspm                     711 non-null    float64

In [10]:
lpl.describe()

,playoffs,game,patch,gamelength,t1_result,t1_firstblood,t1_firstdragon,t1_dragons,t1_elementaldrakes,t1_infernals,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
count,711.000000,711.000000,711.000000,711.000000,711.000000,710.000000,692.000000,711.000000,675.000000,675.000000,...,710.000000,710.000000,710.000000,711.000000,692.000000,692.000000,692.000000,692.000000,692.000000,692.000000
mean,0.064698,1.817159,10.093713,1940.475387,0.530239,0.488732,0.456647,2.392405,2.222222,0.579259,...,15.487324,8.670423,1.802817,7.545782,3260.320809,4535.998555,75.471098,5203.164740,7159.320809,121.541908
std,0.246165,0.785638,0.039724,333.381525,0.499436,0.500225,0.498477,1.476348,1.314531,0.808440,...,12.507791,8.106909,3.440076,1.191906,356.343139,394.768816,11.570111,640.873027,640.706431,16.886434
min,0.000000,1.000000,10.010000,1177.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.094200,2162.000000,3105.000000,24.000000,3782.000000,4882.000000,39.000000
25%,0.000000,1.000000,10.060000,1709.500000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,...,6.000000,3.000000,0.000000,6.780000,3038.750000,4302.750000,69.000000,4771.500000,6729.250000,111.000000
50%,0.000000,2.000000,10.100000,1900.000000,1.000000,0.000000,0.000000,2.000000,2.000000,0.000000,...,13.000000,7.000000,0.000000,7.555100,3226.000000,4582.000000,77.000000,5115.500000,7229.500000,123.000000
75%,0.000000,2.000000,10.130000,2121.000000,1.000000,1.000000,1.000000,3.000000,3.000000,1.000000,...,22.000000,13.000000,2.000000,8.265900,3445.500000,4822.250000,83.000000,5564.250000,7619.250000,133.000000
max,1.000000,5.000000,10.160000,3251.000000,1.000000,1.000000,1.000000,10.000000,4.000000,4.000000,...,76.000000,52.000000,27.000000,11.822200,4728.000000,5600.000000,101.000000,7563.000000,8930.000000,171.000000

In [11]:
lpl.shape

(711, 408)

In [12]:
# Cardinalidad
for i in lpl.select_dtypes(include=object):
    print(f"La cardinalidad de la variable {i} es {(lpl[i].nunique()/lpl.shape[0])*100:.2f}%")

La cardinalidad de la variable date es 100.00%
La cardinalidad de la variable gameId es 100.00%
La cardinalidad de la variable league es 0.14%
La cardinalidad de la variable split es 0.28%
La cardinalidad de la variable t1_playerid es 2.39%
La cardinalidad de la variable t1_ban1 es 7.31%
La cardinalidad de la variable t1_ban2 es 8.16%
La cardinalidad de la variable t1_ban3 es 8.72%
La cardinalidad de la variable t1_ban4 es 10.69%
La cardinalidad de la variable t1_ban5 es 11.39%
La cardinalidad de la variable t2_playerid es 2.39%
La cardinalidad de la variable t2_ban1 es 6.05%
La cardinalidad de la variable t2_ban2 es 6.89%
La cardinalidad de la variable t2_ban3 es 8.44%
La cardinalidad de la variable t2_ban4 es 11.11%
La cardinalidad de la variable t2_ban5 es 11.53%
La cardinalidad de la variable t1p1_position es 0.14%
La cardinalidad de la variable t1p1_player es 4.08%
La cardinalidad de la variable t1p1_team es 2.39%
La cardinalidad de la variable t1p1_champion es 4.08%
La cardinalidad de la variable t1p2_position es 0.14%
La cardinalidad de la variable t1p2_player es 4.22%
La cardinalidad de la variable t1p2_team es 2.39%
La cardinalidad de la variable t1p2_champion es 2.95%
La cardinalidad de la variable t1p3_position es 0.14%
La cardinalidad de la variable t1p3_player es 3.38%
La cardinalidad de la variable t1p3_team es 2.39%
La cardinalidad de la variable t1p3_champion es 5.63%
La cardinalidad de la variable t1p4_position es 0.14%
La cardinalidad de la variable t1p4_player es 3.66%
La cardinalidad de la variable t1p4_team es 2.39%
La cardinalidad de la variable t1p4_champion es 3.66%
La cardinalidad de la variable t1p5_position es 0.14%
La cardinalidad de la variable t1p5_player es 4.64%
La cardinalidad de la variable t1p5_team es 2.39%
La cardinalidad de la variable t1p5_champion es 5.20%
La cardinalidad de la variable t2p1_position es 0.14%
La cardinalidad de la variable t2p1_player es 4.08%
La cardinalidad de la variable t2p1_team es 2.39%
La cardinalidad de la variable t2p1_champion es 3.94%
La cardinalidad de la variable t2p2_position es 0.14%
La cardinalidad de la variable t2p2_player es 4.08%
La cardinalidad de la variable t2p2_team es 2.39%
La cardinalidad de la variable t2p2_champion es 2.67%
La cardinalidad de la variable t2p3_position es 0.14%
La cardinalidad de la variable t2p3_player es 3.38%
La cardinalidad de la variable t2p3_team es 2.39%
La cardinalidad de la variable t2p3_champion es 6.19%
La cardinalidad de la variable t2p4_position es 0.14%
La cardinalidad de la variable t2p4_player es 3.80%
La cardinalidad de la variable t2p4_team es 2.39%
La cardinalidad de la variable t2p4_champion es 3.38%
La cardinalidad de la variable t2p5_position es 0.14%
La cardinalidad de la variable t2p5_player es 4.36%
La cardinalidad de la variable t2p5_team es 2.39%
La cardinalidad de la variable t2p5_champion es 4.50%

#### LCK

In [14]:
lck = S10_dataset[S10_dataset["league"] == "LCK"]

In [15]:
lck.head()

,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,t1_ban1,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
184,2020-02-05 06:34:00,1302595,LCK,Spring,0,1,10.02,2441,T1,Syndra,...,42.0,25.0,4.0,7.9394,3541.0,4810.0,81.0,5188.0,7068.0,126.0
185,2020-02-05 09:00:00,1302628,LCK,Spring,0,2,10.02,2870,DAMWON Gaming,Rek'Sai,...,32.0,24.0,4.0,7.9024,3477.0,4650.0,75.0,5558.0,8287.0,128.0
186,2020-02-05 10:14:00,1302635,LCK,Spring,0,3,10.02,2837,T1,Mordekaiser,...,56.0,27.0,15.0,10.1727,2997.0,4417.0,73.0,4730.0,7102.0,123.0
187,2020-02-05 11:33:00,1302651,LCK,Spring,0,1,10.02,1748,KT Rolster,Irelia,...,9.0,9.0,0.0,7.7231,3032.0,4370.0,77.0,4717.0,7416.0,129.0
188,2020-02-05 13:10:00,1292960,LCK,Spring,0,2,10.02,1609,Gen.G,Olaf,...,13.0,12.0,1.0,7.8682,3021.0,4535.0,73.0,4907.0,7626.0,127.0

In [16]:
lck.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 441 entries, 184 to 5087
Data columns (total 408 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    date                          441 non-null    object
 1    gameId                        441 non-null    object
 2    league                        441 non-null    object
 3    split                         429 non-null    object
 4    playoffs                      441 non-null    int64
 5    game                          441 non-null    int64
 6    patch                         441 non-null    float64
 7    gamelength                    441 non-null    int64
 8    t1_playerid                   441 non-null    object
 9    t1_ban1                       440 non-null    object
 10   t1_ban2                       440 non-null    object
 11   t1_ban3                       441 non-null    object
 12   t1_ban4                       441 non-null    object
 13   t1_ban5                       441 non-null    object
 14   t1_result                     441 non-null    int64
 15   t1_firstblood                 441 non-null    float64
 16   t1_firstdragon                441 non-null    float64
 17   t1_dragons                    441 non-null    int64
 18   t1_elementaldrakes            438 non-null    float64
 19   t1_infernals                  438 non-null    float64
 20   t1_mountains                  438 non-null    float64
 21   t1_clouds                     438 non-null    float64
 22   t1_oceans                     438 non-null    float64
 23   t1_elders                     441 non-null    float64
 24   t1_firstherald                441 non-null    float64
 25   t1_heralds                    441 non-null    float64
 26   t1_firstbaron                 441 non-null    float64
 27   t1_barons                     441 non-null    int64
 28   t1_firsttower                 441 non-null    float64
 29   t1_towers                     441 non-null    int64
 30   t1_firstmidtower              439 non-null    float64
 31   t1_firsttothreetowers         441 non-null    float64
 32   t1_inhibitors                 441 non-null    float64
 33   t2_playerid                   441 non-null    object
 34   t2_ban1                       441 non-null    object
 35   t2_ban2                       441 non-null    object
 36   t2_ban3                       440 non-null    object
 37   t2_ban4                       440 non-null    object
 38   t2_ban5                       440 non-null    object
 39   t2_result                     441 non-null    int64
 40   t2_firstblood                 441 non-null    float64
 41   t2_firstdragon                441 non-null    float64
 42   t2_dragons                    441 non-null    int64
 43   t2_elementaldrakes            438 non-null    float64
 44   t2_infernals                  438 non-null    float64
 45   t2_mountains                  438 non-null    float64
 46   t2_clouds                     438 non-null    float64
 47   t2_oceans                     438 non-null    float64
 48   t2_elders                     441 non-null    float64
 49   t2_firstherald                441 non-null    float64
 50   t2_heralds                    441 non-null    float64
 51   t2_firstbaron                 441 non-null    float64
 52   t2_barons                     441 non-null    int64
 53   t2_firsttower                 441 non-null    float64
 54   t2_towers                     441 non-null    int64
 55   t2_firstmidtower              439 non-null    float64
 56   t2_firsttothreetowers         441 non-null    float64
 57   t2_inhibitors                 441 non-null    float64
 58   t1p1_position                 441 non-null    object
 59   t1p1_player                   441 non-null    object
 60   t1p1_team                     441 non-null    object
 61   t1p1_champion                 441 non-null    object
 62   t1p1_kills                    441 non-null    int64
 63   t1p1_deaths                   441 non-null    int64
 64   t1p1_assists                  441 non-null    int64
 65   t1p1_firstblood               441 non-null    float64
 66   t1p1_firstbloodkill           441 non-null    float64
 67   t1p1_firstbloodassist         441 non-null    float64
 68   t1p1_firstbloodvictim         441 non-null    float64
 69   t1p1_damagetochampions        441 non-null    float64
 70   t1p1_dpm                      441 non-null    float64
 71   t1p1_wardsplaced              441 non-null    float64
 72   t1p1_wpm                      441 non-null    float64
 73   t1p1_wardskilled              441 non-null    float64
 74   t1p1_wcpm                     441 non-null    float64
 75   t1p1_controlwardsbought       441 non-null    float64
 76   t1p1_visionscore              441 non-null    float64
 77   t1p1_vspm                     441 non-null    float64
 78   t1p1_totalgold                441 non-null    int64
 79   t1p1_earnedgold               441 non-null    int64
 80   t1p1_earned gpm               441 non-null    float64
 81   t1p1_goldspent                441 non-null    float64
 82   t1p1_minionkills              441 non-null    float64
 83   t1p1_monsterkills             441 non-null    float64
 84   t1p1_monsterkillsownjungle    441 non-null    float64
 85   t1p1_monsterkillsenemyjungle  441 non-null    float64
 86   t1p1_cspm                     441 non-null    float64
 87   t1p1_goldat10                 441 non-null    float64
 88   t1p1pat10                     441 non-null    float64
 89   t1p1_csat10                   441 non-null    float64
 90   t1p1_goldat15                 439 non-null    float64
 91   t1p1pat15                     439 non-null    float64
 92   t1p1_csat15                   439 non-null    float64
 93   t1p2_position                 441 non-null    object
 94   t1p2_player                   441 non-null    object
 95   t1p2_team                     441 non-null    object
 96   t1p2_champion                 441 non-null    object
 97   t1p2_kills                    441 non-null    int64
 98   t1p2_deaths                   441 non-null    int64
 99   t1p2_assists                  441 non-null    int64
 100  t1p2_firstblood               441 non-null    float64
 101  t1p2_firstbloodkill           441 non-null    float64
 102  t1p2_firstbloodassist         441 non-null    float64
 103  t1p2_firstbloodvictim         441 non-null    float64
 104  t1p2_damagetochampions        441 non-null    float64
 105  t1p2_dpm                      441 non-null    float64
 106  t1p2_wardsplaced              441 non-null    float64
 107  t1p2_wpm                      441 non-null    float64
 108  t1p2_wardskilled              441 non-null    float64
 109  t1p2_wcpm                     441 non-null    float64
 110  t1p2_controlwardsbought       441 non-null    float64
 111  t1p2_visionscore              441 non-null    float64
 112  t1p2_vspm                     441 non-null    float64
 113  t1p2_totalgold                441 non-null    int64
 114  t1p2_earnedgold               441 non-null    int64
 115  t1p2_earned gpm               441 non-null    float64
 116  t1p2_goldspent                441 non-null    float64
 117  t1p2_minionkills              441 non-null    float64
 118  t1p2_monsterkills             441 non-null    float64
 119  t1p2_monsterkillsownjungle    441 non-null    float64
 120  t1p2_monsterkillsenemyjungle  441 non-null    float64
 121  t1p2_cspm                     441 non-null    float64
 122  t1p2_goldat10                 441 non-null    float64
 123  t1p2pat10                     441 non-null    float64
 124  t1p2_csat10                   441 non-null    float64
 125  t1p2_goldat15                 439 non-null    float64
 126  t1p2pat15                     439 non-null    float64
 127  t1p2_csat15                   439 non-null    float64
 128  t1p3_position                 441 non-null    object
 129  t1p3_player                   441 non-null    object
 130  t1p3_team                     441 non-null    object
 131  t1p3_champion                 441 non-null    object
 132  t1p3_kills                    441 non-null    int64
 133  t1p3_deaths                   441 non-null    int64
 134  t1p3_assists                  441 non-null    int64
 135  t1p3_firstblood               441 non-null    float64
 136  t1p3_firstbloodkill           441 non-null    float64
 137  t1p3_firstbloodassist         441 non-null    float64
 138  t1p3_firstbloodvictim         441 non-null    float64
 139  t1p3_damagetochampions        441 non-null    float64
 140  t1p3_dpm                      441 non-null    float64
 141  t1p3_wardsplaced              441 non-null    float64
 142  t1p3_wpm                      441 non-null    float64
 143  t1p3_wardskilled              441 non-null    float64
 144  t1p3_wcpm                     441 non-null    float64
 145  t1p3_controlwardsbought       441 non-null    float64
 146  t1p3_visionscore              441 non-null    float64
 147  t1p3_vspm                     441 non-null    float64
 148  t1p3_totalgold                441 non-null    int64
 149  t1p3_earnedgold               441 non-null    int64
 150  t1p3_earned gpm               441 non-null    float64
 151  t1p3_goldspent                441 non-null    float64
 152  t1p3_minionkills              441 non-null    float64
 153  t1p3_monsterkills             441 non-null    float64
 154  t1p3_monsterkillsownjungle    441 non-null    float64
 155  t1p3_monsterkillsenemyjungle  441 non-null    float64
 156  t1p3_cspm                     441 non-null    float64
 157  t1p3_goldat10                 441 non-null    float64
 158  t1p3pat10                     441 non-null    float64
 159  t1p3_csat10                   441 non-null    float64
 160  t1p3_goldat15                 439 non-null    float64
 161  t1p3pat15                     439 non-null    float64
 162  t1p3_csat15                   439 non-null    float64
 163  t1p4_position                 441 non-null    object
 164  t1p4_player                   441 non-null    object
 165  t1p4_team                     441 non-null    object
 166  t1p4_champion                 441 non-null    object
 167  t1p4_kills                    441 non-null    int64
 168  t1p4_deaths                   441 non-null    int64
 169  t1p4_assists                  441 non-null    int64
 170  t1p4_firstblood               441 non-null    float64
 171  t1p4_firstbloodkill           441 non-null    float64
 172  t1p4_firstbloodassist         441 non-null    float64
 173  t1p4_firstbloodvictim         441 non-null    float64
 174  t1p4_damagetochampions        441 non-null    float64
 175  t1p4_dpm                      441 non-null    float64
 176  t1p4_wardsplaced              441 non-null    float64
 177  t1p4_wpm                      441 non-null    float64
 178  t1p4_wardskilled              441 non-null    float64
 179  t1p4_wcpm                     441 non-null    float64
 180  t1p4_controlwardsbought       441 non-null    float64
 181  t1p4_visionscore              441 non-null    float64
 182  t1p4_vspm                     441 non-null    float64
 183  t1p4_totalgold                441 non-null    int64
 184  t1p4_earnedgold               441 non-null    int64
 185  t1p4_earned gpm               441 non-null    float64
 186  t1p4_goldspent                441 non-null    float64
 187  t1p4_minionkills              441 non-null    float64
 188  t1p4_monsterkills             441 non-null    float64
 189  t1p4_monsterkillsownjungle    441 non-null    float64
 190  t1p4_monsterkillsenemyjungle  441 non-null    float64
 191  t1p4_cspm                     441 non-null    float64
 192  t1p4_goldat10                 441 non-null    float64
 193  t1p4pat10                     441 non-null    float64
 194  t1p4_csat10                   441 non-null    float64
 195  t1p4_goldat15                 439 non-null    float64
 196  t1p4pat15                     439 non-null    float64
 197  t1p4_csat15                   439 non-null    float64
 198  t1p5_position                 441 non-null    object
 199  t1p5_player                   441 non-null    object
 200  t1p5_team                     441 non-null    object
 201  t1p5_champion                 441 non-null    object
 202  t1p5_kills                    441 non-null    int64
 203  t1p5_deaths                   441 non-null    int64
 204  t1p5_assists                  441 non-null    int64
 205  t1p5_firstblood               441 non-null    float64
 206  t1p5_firstbloodkill           441 non-null    float64
 207  t1p5_firstbloodassist         441 non-null    float64
 208  t1p5_firstbloodvictim         441 non-null    float64
 209  t1p5_damagetochampions        441 non-null    float64
 210  t1p5_dpm                      441 non-null    float64
 211  t1p5_wardsplaced              441 non-null    float64
 212  t1p5_wpm                      441 non-null    float64
 213  t1p5_wardskilled              441 non-null    float64
 214  t1p5_wcpm                     441 non-null    float64
 215  t1p5_controlwardsbought       441 non-null    float64
 216  t1p5_visionscore              441 non-null    float64
 217  t1p5_vspm                     441 non-null    float64
 218  t1p5_totalgold                441 non-null    int64
 219  t1p5_earnedgold               441 non-null    int64
 220  t1p5_earned gpm               441 non-null    float64
 221  t1p5_goldspent                441 non-null    float64
 222  t1p5_minionkills              441 non-null    float64
 223  t1p5_monsterkills             441 non-null    float64
 224  t1p5_monsterkillsownjungle    441 non-null    float64
 225  t1p5_monsterkillsenemyjungle  441 non-null    float64
 226  t1p5_cspm                     441 non-null    float64
 227  t1p5_goldat10                 441 non-null    float64
 228  t1p5pat10                     441 non-null    float64
 229  t1p5_csat10                   441 non-null    float64
 230  t1p5_goldat15                 439 non-null    float64
 231  t1p5pat15                     439 non-null    float64
 232  t1p5_csat15                   439 non-null    float64
 233  t2p1_position                 441 non-null    object
 234  t2p1_player                   441 non-null    object
 235  t2p1_team                     441 non-null    object
 236  t2p1_champion                 441 non-null    object
 237  t2p1_kills                    441 non-null    int64
 238  t2p1_deaths                   441 non-null    int64
 239  t2p1_assists                  441 non-null    int64
 240  t2p1_firstblood               441 non-null    float64
 241  t2p1_firstbloodkill           441 non-null    float64
 242  t2p1_firstbloodassist         441 non-null    float64
 243  t2p1_firstbloodvictim         441 non-null    float64
 244  t2p1_damagetochampions        441 non-null    float64
 245  t2p1_dpm                      441 non-null    float64
 246  t2p1_wardsplaced              441 non-null    float64
 247  t2p1_wpm                      441 non-null    float64
 248  t2p1_wardskilled              441 non-null    float64
 249  t2p1_wcpm                     441 non-null    float64
 250  t2p1_controlwardsbought       441 non-null    float64
 251  t2p1_visionscore              441 non-null    float64
 252  t2p1_vspm                     441 non-null    float64
 253  t2p1_totalgold                441 non-null    int64
 254  t2p1_earnedgold               441 non-null    int64
 255  t2p1_earned gpm               441 non-null    float64
 256  t2p1_goldspent                441 non-null    float64
 257  t2p1_minionkills              441 non-null    float64
 258  t2p1_monsterkills             441 non-null    float64
 259  t2p1_monsterkillsownjungle    441 non-null    float64
 260  t2p1_monsterkillsenemyjungle  441 non-null    float64
 261  t2p1_cspm                     441 non-null    float64
 262  t2p1_goldat10                 441 non-null    float64
 263  t2p1pat10                     441 non-null    float64
 264  t2p1_csat10                   441 non-null    float64
 265  t2p1_goldat15                 439 non-null    float64
 266  t2p1pat15                     439 non-null    float64
 267  t2p1_csat15                   439 non-null    float64
 268  t2p2_position                 441 non-null    object
 269  t2p2_player                   441 non-null    object
 270  t2p2_team                     441 non-null    object
 271  t2p2_champion                 441 non-null    object
 272  t2p2_kills                    441 non-null    int64
 273  t2p2_deaths                   441 non-null    int64
 274  t2p2_assists                  441 non-null    int64
 275  t2p2_firstblood               441 non-null    float64
 276  t2p2_firstbloodkill           441 non-null    float64
 277  t2p2_firstbloodassist         441 non-null    float64
 278  t2p2_firstbloodvictim         441 non-null    float64
 279  t2p2_damagetochampions        441 non-null    float64
 280  t2p2_dpm                      441 non-null    float64
 281  t2p2_wardsplaced              441 non-null    float64
 282  t2p2_wpm                      441 non-null    float64
 283  t2p2_wardskilled              441 non-null    float64
 284  t2p2_wcpm                     441 non-null    float64
 285  t2p2_controlwardsbought       441 non-null    float64
 286  t2p2_visionscore              441 non-null    float64
 287  t2p2_vspm                     441 non-null    float64
 288  t2p2_totalgold                441 non-null    int64
 289  t2p2_earnedgold               441 non-null    int64
 290  t2p2_earned gpm               441 non-null    float64
 291  t2p2_goldspent                441 non-null    float64
 292  t2p2_minionkills              441 non-null    float64
 293  t2p2_monsterkills             441 non-null    float64
 294  t2p2_monsterkillsownjungle    441 non-null    float64
 295  t2p2_monsterkillsenemyjungle  441 non-null    float64
 296  t2p2_cspm                     441 non-null    float64
 297  t2p2_goldat10                 441 non-null    float64
 298  t2p2pat10                     441 non-null    float64
 299  t2p2_csat10                   441 non-null    float64
 300  t2p2_goldat15                 439 non-null    float64
 301  t2p2pat15                     439 non-null    float64
 302  t2p2_csat15                   439 non-null    float64
 303  t2p3_position                 441 non-null    object
 304  t2p3_player                   441 non-null    object
 305  t2p3_team                     441 non-null    object
 306  t2p3_champion                 441 non-null    object
 307  t2p3_kills                    441 non-null    int64
 308  t2p3_deaths                   441 non-null    int64
 309  t2p3_assists                  441 non-null    int64
 310  t2p3_firstblood               441 non-null    float64
 311  t2p3_firstbloodkill           441 non-null    float64
 312  t2p3_firstbloodassist         441 non-null    float64
 313  t2p3_firstbloodvictim         441 non-null    float64
 314  t2p3_damagetochampions        441 non-null    float64
 315  t2p3_dpm                      441 non-null    float64
 316  t2p3_wardsplaced              441 non-null    float64
 317  t2p3_wpm                      441 non-null    float64
 318  t2p3_wardskilled              441 non-null    float64
 319  t2p3_wcpm                     441 non-null    float64
 320  t2p3_controlwardsbought       441 non-null    float64
 321  t2p3_visionscore              441 non-null    float64
 322  t2p3_vspm                     441 non-null    float64
 323  t2p3_totalgold                441 non-null    int64
 324  t2p3_earnedgold               441 non-null    int64
 325  t2p3_earned gpm               441 non-null    float64
 326  t2p3_goldspent                441 non-null    float64
 327  t2p3_minionkills              441 non-null    float64
 328  t2p3_monsterkills             441 non-null    float64
 329  t2p3_monsterkillsownjungle    441 non-null    float64
 330  t2p3_monsterkillsenemyjungle  441 non-null    float64
 331  t2p3_cspm                     441 non-null    float64

In [17]:
lck.describe()

,playoffs,game,patch,gamelength,t1_result,t1_firstblood,t1_firstdragon,t1_dragons,t1_elementaldrakes,t1_infernals,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
count,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,438.000000,438.000000,...,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,439.000000,439.000000,439.000000
mean,0.034014,1.777778,10.082222,1965.680272,0.551020,0.510204,0.462585,2.424036,2.344749,0.625571,...,16.684807,9.866213,2.000000,8.052594,3258.993197,4578.882086,78.213152,5165.993166,7233.854214,125.086560
std,0.181470,0.757121,0.045558,344.708665,0.497955,0.500464,0.499164,1.431548,1.341933,0.783984,...,14.436159,9.925530,3.819805,1.265482,351.351000,378.073652,11.608379,617.392331,625.056693,16.930877
min,0.000000,1.000000,10.020000,1014.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.867100,1919.000000,2021.000000,12.000000,2841.000000,3346.000000,19.000000
25%,0.000000,1.000000,10.040000,1714.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,...,6.000000,3.000000,0.000000,7.361500,3062.000000,4402.000000,72.000000,4733.000000,6893.000000,115.000000
50%,0.000000,2.000000,10.070000,1932.000000,1.000000,1.000000,0.000000,3.000000,3.000000,0.000000,...,14.000000,8.000000,0.000000,8.009800,3232.000000,4626.000000,79.000000,5094.000000,7267.000000,126.000000
75%,0.000000,2.000000,10.130000,2176.000000,1.000000,1.000000,1.000000,4.000000,4.000000,1.000000,...,24.000000,15.000000,3.000000,8.902400,3441.000000,4826.000000,86.000000,5490.000000,7665.000000,136.500000
max,1.000000,5.000000,10.150000,3276.000000,1.000000,1.000000,1.000000,6.000000,4.000000,4.000000,...,90.000000,68.000000,23.000000,11.412700,5296.000000,5547.000000,106.000000,7229.000000,8790.000000,165.000000

In [18]:
# Cardinalidad
for i in lck.select_dtypes(include=object):
    print(f"La cardinalidad de la variable {i} es {(lck[i].nunique()/lck.shape[0])*100:.2f}%")

La cardinalidad de la variable date es 100.00%
La cardinalidad de la variable gameId es 100.00%
La cardinalidad de la variable league es 0.23%
La cardinalidad de la variable split es 0.45%
La cardinalidad de la variable t1_playerid es 2.72%
La cardinalidad de la variable t1_ban1 es 10.66%
La cardinalidad de la variable t1_ban2 es 11.79%
La cardinalidad de la variable t1_ban3 es 12.93%
La cardinalidad de la variable t1_ban4 es 16.78%
La cardinalidad de la variable t1_ban5 es 18.59%
La cardinalidad de la variable t2_playerid es 2.72%
La cardinalidad de la variable t2_ban1 es 9.30%
La cardinalidad de la variable t2_ban2 es 10.88%
La cardinalidad de la variable t2_ban3 es 13.15%
La cardinalidad de la variable t2_ban4 es 18.14%
La cardinalidad de la variable t2_ban5 es 17.46%
La cardinalidad de la variable t1p1_position es 0.23%
La cardinalidad de la variable t1p1_player es 4.54%
La cardinalidad de la variable t1p1_team es 2.72%
La cardinalidad de la variable t1p1_champion es 8.39%
La cardinalidad de la variable t1p2_position es 0.23%
La cardinalidad de la variable t1p2_player es 4.08%
La cardinalidad de la variable t1p2_team es 2.72%
La cardinalidad de la variable t1p2_champion es 4.54%
La cardinalidad de la variable t1p3_position es 0.23%
La cardinalidad de la variable t1p3_player es 4.54%
La cardinalidad de la variable t1p3_team es 2.72%
La cardinalidad de la variable t1p3_champion es 10.20%
La cardinalidad de la variable t1p4_position es 0.23%
La cardinalidad de la variable t1p4_player es 4.31%
La cardinalidad de la variable t1p4_team es 2.72%
La cardinalidad de la variable t1p4_champion es 6.58%
La cardinalidad de la variable t1p5_position es 0.23%
La cardinalidad de la variable t1p5_player es 4.54%
La cardinalidad de la variable t1p5_team es 2.72%
La cardinalidad de la variable t1p5_champion es 7.26%
La cardinalidad de la variable t2p1_position es 0.23%
La cardinalidad de la variable t2p1_player es 4.54%
La cardinalidad de la variable t2p1_team es 2.72%
La cardinalidad de la variable t2p1_champion es 7.94%
La cardinalidad de la variable t2p2_position es 0.23%
La cardinalidad de la variable t2p2_player es 4.08%
La cardinalidad de la variable t2p2_team es 2.72%
La cardinalidad de la variable t2p2_champion es 6.35%
La cardinalidad de la variable t2p3_position es 0.23%
La cardinalidad de la variable t2p3_player es 4.76%
La cardinalidad de la variable t2p3_team es 2.72%
La cardinalidad de la variable t2p3_champion es 9.30%
La cardinalidad de la variable t2p4_position es 0.23%
La cardinalidad de la variable t2p4_player es 4.31%
La cardinalidad de la variable t2p4_team es 2.72%
La cardinalidad de la variable t2p4_champion es 5.67%
La cardinalidad de la variable t2p5_position es 0.23%
La cardinalidad de la variable t2p5_player es 4.54%
La cardinalidad de la variable t2p5_team es 2.72%
La cardinalidad de la variable t2p5_champion es 9.75%

#### LEC

In [19]:
lec = S10_dataset[S10_dataset["league"] == "LEC"]

In [20]:
lec.head()

,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,t1_ban1,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
53,2020-01-24 16:17:00,1390161,LEC,Spring,0,1,10.01,2059,G2 Esports,Irelia,...,1.0,1.0,0.0,6.7606,3143.0,4814.0,69.0,5538.0,8084.0,126.0
54,2020-01-24 17:40:00,1390170,LEC,Spring,0,1,10.01,3049,SK Gaming,Lucian,...,22.0,15.0,0.0,6.7891,3218.0,4630.0,84.0,4794.0,7290.0,129.0
55,2020-01-24 19:00:00,1390196,LEC,Spring,0,1,10.01,2544,Rogue,Rumble,...,32.0,32.0,0.0,8.2075,2837.0,4224.0,63.0,4677.0,6490.0,110.0
56,2020-01-24 20:11:00,1390202,LEC,Spring,0,1,10.01,2392,Excel Esports,Thresh,...,9.0,4.0,1.0,6.2709,3665.0,5044.0,90.0,5870.0,8125.0,145.0
57,2020-01-24 21:18:00,1390213,LEC,Spring,0,1,10.01,2554,Fnatic,Lucian,...,23.0,20.0,3.0,8.1049,3175.0,4603.0,77.0,5024.0,7266.0,127.0

In [21]:
lec.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 211 entries, 53 to 4835
Data columns (total 408 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    date                          211 non-null    object
 1    gameId                        211 non-null    object
 2    league                        211 non-null    object
 3    split                         211 non-null    object
 4    playoffs                      211 non-null    int64
 5    game                          211 non-null    int64
 6    patch                         211 non-null    float64
 7    gamelength                    211 non-null    int64
 8    t1_playerid                   211 non-null    object
 9    t1_ban1                       211 non-null    object
 10   t1_ban2                       211 non-null    object
 11   t1_ban3                       210 non-null    object
 12   t1_ban4                       211 non-null    object
 13   t1_ban5                       210 non-null    object
 14   t1_result                     211 non-null    int64
 15   t1_firstblood                 211 non-null    float64
 16   t1_firstdragon                210 non-null    float64
 17   t1_dragons                    211 non-null    int64
 18   t1_elementaldrakes            210 non-null    float64
 19   t1_infernals                  210 non-null    float64
 20   t1_mountains                  210 non-null    float64
 21   t1_clouds                     210 non-null    float64
 22   t1_oceans                     210 non-null    float64
 23   t1_elders                     211 non-null    float64
 24   t1_firstherald                211 non-null    float64
 25   t1_heralds                    211 non-null    float64
 26   t1_firstbaron                 211 non-null    float64
 27   t1_barons                     211 non-null    int64
 28   t1_firsttower                 211 non-null    float64
 29   t1_towers                     211 non-null    int64
 30   t1_firstmidtower              210 non-null    float64
 31   t1_firsttothreetowers         211 non-null    float64
 32   t1_inhibitors                 211 non-null    float64
 33   t2_playerid                   211 non-null    object
 34   t2_ban1                       211 non-null    object
 35   t2_ban2                       211 non-null    object
 36   t2_ban3                       211 non-null    object
 37   t2_ban4                       211 non-null    object
 38   t2_ban5                       211 non-null    object
 39   t2_result                     211 non-null    int64
 40   t2_firstblood                 211 non-null    float64
 41   t2_firstdragon                210 non-null    float64
 42   t2_dragons                    211 non-null    int64
 43   t2_elementaldrakes            210 non-null    float64
 44   t2_infernals                  210 non-null    float64
 45   t2_mountains                  210 non-null    float64
 46   t2_clouds                     210 non-null    float64
 47   t2_oceans                     210 non-null    float64
 48   t2_elders                     211 non-null    float64
 49   t2_firstherald                211 non-null    float64
 50   t2_heralds                    211 non-null    float64
 51   t2_firstbaron                 211 non-null    float64
 52   t2_barons                     211 non-null    int64
 53   t2_firsttower                 211 non-null    float64
 54   t2_towers                     211 non-null    int64
 55   t2_firstmidtower              210 non-null    float64
 56   t2_firsttothreetowers         211 non-null    float64
 57   t2_inhibitors                 211 non-null    float64
 58   t1p1_position                 211 non-null    object
 59   t1p1_player                   211 non-null    object
 60   t1p1_team                     211 non-null    object
 61   t1p1_champion                 211 non-null    object
 62   t1p1_kills                    211 non-null    int64
 63   t1p1_deaths                   211 non-null    int64
 64   t1p1_assists                  211 non-null    int64
 65   t1p1_firstblood               211 non-null    float64
 66   t1p1_firstbloodkill           211 non-null    float64
 67   t1p1_firstbloodassist         211 non-null    float64
 68   t1p1_firstbloodvictim         211 non-null    float64
 69   t1p1_damagetochampions        211 non-null    float64
 70   t1p1_dpm                      211 non-null    float64
 71   t1p1_wardsplaced              211 non-null    float64
 72   t1p1_wpm                      211 non-null    float64
 73   t1p1_wardskilled              211 non-null    float64
 74   t1p1_wcpm                     211 non-null    float64
 75   t1p1_controlwardsbought       211 non-null    float64
 76   t1p1_visionscore              211 non-null    float64
 77   t1p1_vspm                     211 non-null    float64
 78   t1p1_totalgold                211 non-null    int64
 79   t1p1_earnedgold               211 non-null    int64
 80   t1p1_earned gpm               211 non-null    float64
 81   t1p1_goldspent                211 non-null    float64
 82   t1p1_minionkills              211 non-null    float64
 83   t1p1_monsterkills             211 non-null    float64
 84   t1p1_monsterkillsownjungle    211 non-null    float64
 85   t1p1_monsterkillsenemyjungle  211 non-null    float64
 86   t1p1_cspm                     211 non-null    float64
 87   t1p1_goldat10                 210 non-null    float64
 88   t1p1pat10                     210 non-null    float64
 89   t1p1_csat10                   210 non-null    float64
 90   t1p1_goldat15                 210 non-null    float64
 91   t1p1pat15                     210 non-null    float64
 92   t1p1_csat15                   210 non-null    float64
 93   t1p2_position                 211 non-null    object
 94   t1p2_player                   211 non-null    object
 95   t1p2_team                     211 non-null    object
 96   t1p2_champion                 211 non-null    object
 97   t1p2_kills                    211 non-null    int64
 98   t1p2_deaths                   211 non-null    int64
 99   t1p2_assists                  211 non-null    int64
 100  t1p2_firstblood               211 non-null    float64
 101  t1p2_firstbloodkill           211 non-null    float64
 102  t1p2_firstbloodassist         211 non-null    float64
 103  t1p2_firstbloodvictim         211 non-null    float64
 104  t1p2_damagetochampions        211 non-null    float64
 105  t1p2_dpm                      211 non-null    float64
 106  t1p2_wardsplaced              211 non-null    float64
 107  t1p2_wpm                      211 non-null    float64
 108  t1p2_wardskilled              211 non-null    float64
 109  t1p2_wcpm                     211 non-null    float64
 110  t1p2_controlwardsbought       211 non-null    float64
 111  t1p2_visionscore              211 non-null    float64
 112  t1p2_vspm                     211 non-null    float64
 113  t1p2_totalgold                211 non-null    int64
 114  t1p2_earnedgold               211 non-null    int64
 115  t1p2_earned gpm               211 non-null    float64
 116  t1p2_goldspent                211 non-null    float64
 117  t1p2_minionkills              211 non-null    float64
 118  t1p2_monsterkills             211 non-null    float64
 119  t1p2_monsterkillsownjungle    211 non-null    float64
 120  t1p2_monsterkillsenemyjungle  211 non-null    float64
 121  t1p2_cspm                     211 non-null    float64
 122  t1p2_goldat10                 210 non-null    float64
 123  t1p2pat10                     210 non-null    float64
 124  t1p2_csat10                   210 non-null    float64
 125  t1p2_goldat15                 210 non-null    float64
 126  t1p2pat15                     210 non-null    float64
 127  t1p2_csat15                   210 non-null    float64
 128  t1p3_position                 211 non-null    object
 129  t1p3_player                   211 non-null    object
 130  t1p3_team                     211 non-null    object
 131  t1p3_champion                 211 non-null    object
 132  t1p3_kills                    211 non-null    int64
 133  t1p3_deaths                   211 non-null    int64
 134  t1p3_assists                  211 non-null    int64
 135  t1p3_firstblood               211 non-null    float64
 136  t1p3_firstbloodkill           211 non-null    float64
 137  t1p3_firstbloodassist         211 non-null    float64
 138  t1p3_firstbloodvictim         211 non-null    float64
 139  t1p3_damagetochampions        211 non-null    float64
 140  t1p3_dpm                      211 non-null    float64
 141  t1p3_wardsplaced              211 non-null    float64
 142  t1p3_wpm                      211 non-null    float64
 143  t1p3_wardskilled              211 non-null    float64
 144  t1p3_wcpm                     211 non-null    float64
 145  t1p3_controlwardsbought       211 non-null    float64
 146  t1p3_visionscore              211 non-null    float64
 147  t1p3_vspm                     211 non-null    float64
 148  t1p3_totalgold                211 non-null    int64
 149  t1p3_earnedgold               211 non-null    int64
 150  t1p3_earned gpm               211 non-null    float64
 151  t1p3_goldspent                211 non-null    float64
 152  t1p3_minionkills              211 non-null    float64
 153  t1p3_monsterkills             211 non-null    float64
 154  t1p3_monsterkillsownjungle    211 non-null    float64
 155  t1p3_monsterkillsenemyjungle  211 non-null    float64
 156  t1p3_cspm                     211 non-null    float64
 157  t1p3_goldat10                 210 non-null    float64
 158  t1p3pat10                     210 non-null    float64
 159  t1p3_csat10                   210 non-null    float64
 160  t1p3_goldat15                 210 non-null    float64
 161  t1p3pat15                     210 non-null    float64
 162  t1p3_csat15                   210 non-null    float64
 163  t1p4_position                 211 non-null    object
 164  t1p4_player                   211 non-null    object
 165  t1p4_team                     211 non-null    object
 166  t1p4_champion                 211 non-null    object
 167  t1p4_kills                    211 non-null    int64
 168  t1p4_deaths                   211 non-null    int64
 169  t1p4_assists                  211 non-null    int64
 170  t1p4_firstblood               211 non-null    float64
 171  t1p4_firstbloodkill           211 non-null    float64
 172  t1p4_firstbloodassist         211 non-null    float64
 173  t1p4_firstbloodvictim         211 non-null    float64
 174  t1p4_damagetochampions        211 non-null    float64
 175  t1p4_dpm                      211 non-null    float64
 176  t1p4_wardsplaced              211 non-null    float64
 177  t1p4_wpm                      211 non-null    float64
 178  t1p4_wardskilled              211 non-null    float64
 179  t1p4_wcpm                     211 non-null    float64
 180  t1p4_controlwardsbought       211 non-null    float64
 181  t1p4_visionscore              211 non-null    float64
 182  t1p4_vspm                     211 non-null    float64
 183  t1p4_totalgold                211 non-null    int64
 184  t1p4_earnedgold               211 non-null    int64
 185  t1p4_earned gpm               211 non-null    float64
 186  t1p4_goldspent                211 non-null    float64
 187  t1p4_minionkills              211 non-null    float64
 188  t1p4_monsterkills             211 non-null    float64
 189  t1p4_monsterkillsownjungle    211 non-null    float64
 190  t1p4_monsterkillsenemyjungle  211 non-null    float64
 191  t1p4_cspm                     211 non-null    float64
 192  t1p4_goldat10                 210 non-null    float64
 193  t1p4pat10                     210 non-null    float64
 194  t1p4_csat10                   210 non-null    float64
 195  t1p4_goldat15                 210 non-null    float64
 196  t1p4pat15                     210 non-null    float64
 197  t1p4_csat15                   210 non-null    float64
 198  t1p5_position                 211 non-null    object
 199  t1p5_player                   211 non-null    object
 200  t1p5_team                     211 non-null    object
 201  t1p5_champion                 211 non-null    object
 202  t1p5_kills                    211 non-null    int64
 203  t1p5_deaths                   211 non-null    int64
 204  t1p5_assists                  211 non-null    int64
 205  t1p5_firstblood               211 non-null    float64
 206  t1p5_firstbloodkill           211 non-null    float64
 207  t1p5_firstbloodassist         211 non-null    float64
 208  t1p5_firstbloodvictim         211 non-null    float64
 209  t1p5_damagetochampions        211 non-null    float64
 210  t1p5_dpm                      211 non-null    float64
 211  t1p5_wardsplaced              211 non-null    float64
 212  t1p5_wpm                      211 non-null    float64
 213  t1p5_wardskilled              211 non-null    float64
 214  t1p5_wcpm                     211 non-null    float64
 215  t1p5_controlwardsbought       211 non-null    float64
 216  t1p5_visionscore              211 non-null    float64
 217  t1p5_vspm                     211 non-null    float64
 218  t1p5_totalgold                211 non-null    int64
 219  t1p5_earnedgold               211 non-null    int64
 220  t1p5_earned gpm               211 non-null    float64
 221  t1p5_goldspent                211 non-null    float64
 222  t1p5_minionkills              211 non-null    float64
 223  t1p5_monsterkills             211 non-null    float64
 224  t1p5_monsterkillsownjungle    211 non-null    float64
 225  t1p5_monsterkillsenemyjungle  211 non-null    float64
 226  t1p5_cspm                     211 non-null    float64
 227  t1p5_goldat10                 210 non-null    float64
 228  t1p5pat10                     210 non-null    float64
 229  t1p5_csat10                   210 non-null    float64
 230  t1p5_goldat15                 210 non-null    float64
 231  t1p5pat15                     210 non-null    float64
 232  t1p5_csat15                   210 non-null    float64
 233  t2p1_position                 211 non-null    object
 234  t2p1_player                   211 non-null    object
 235  t2p1_team                     211 non-null    object
 236  t2p1_champion                 211 non-null    object
 237  t2p1_kills                    211 non-null    int64
 238  t2p1_deaths                   211 non-null    int64
 239  t2p1_assists                  211 non-null    int64
 240  t2p1_firstblood               211 non-null    float64
 241  t2p1_firstbloodkill           211 non-null    float64
 242  t2p1_firstbloodassist         211 non-null    float64
 243  t2p1_firstbloodvictim         211 non-null    float64
 244  t2p1_damagetochampions        211 non-null    float64
 245  t2p1_dpm                      211 non-null    float64
 246  t2p1_wardsplaced              211 non-null    float64
 247  t2p1_wpm                      211 non-null    float64
 248  t2p1_wardskilled              211 non-null    float64
 249  t2p1_wcpm                     211 non-null    float64
 250  t2p1_controlwardsbought       211 non-null    float64
 251  t2p1_visionscore              211 non-null    float64
 252  t2p1_vspm                     211 non-null    float64
 253  t2p1_totalgold                211 non-null    int64
 254  t2p1_earnedgold               211 non-null    int64
 255  t2p1_earned gpm               211 non-null    float64
 256  t2p1_goldspent                211 non-null    float64
 257  t2p1_minionkills              211 non-null    float64
 258  t2p1_monsterkills             211 non-null    float64
 259  t2p1_monsterkillsownjungle    211 non-null    float64
 260  t2p1_monsterkillsenemyjungle  211 non-null    float64
 261  t2p1_cspm                     211 non-null    float64
 262  t2p1_goldat10                 210 non-null    float64
 263  t2p1pat10                     210 non-null    float64
 264  t2p1_csat10                   210 non-null    float64
 265  t2p1_goldat15                 210 non-null    float64
 266  t2p1pat15                     210 non-null    float64
 267  t2p1_csat15                   210 non-null    float64
 268  t2p2_position                 211 non-null    object
 269  t2p2_player                   211 non-null    object
 270  t2p2_team                     211 non-null    object
 271  t2p2_champion                 211 non-null    object
 272  t2p2_kills                    211 non-null    int64
 273  t2p2_deaths                   211 non-null    int64
 274  t2p2_assists                  211 non-null    int64
 275  t2p2_firstblood               211 non-null    float64
 276  t2p2_firstbloodkill           211 non-null    float64
 277  t2p2_firstbloodassist         211 non-null    float64
 278  t2p2_firstbloodvictim         211 non-null    float64
 279  t2p2_damagetochampions        211 non-null    float64
 280  t2p2_dpm                      211 non-null    float64
 281  t2p2_wardsplaced              211 non-null    float64
 282  t2p2_wpm                      211 non-null    float64
 283  t2p2_wardskilled              211 non-null    float64
 284  t2p2_wcpm                     211 non-null    float64
 285  t2p2_controlwardsbought       211 non-null    float64
 286  t2p2_visionscore              211 non-null    float64
 287  t2p2_vspm                     211 non-null    float64
 288  t2p2_totalgold                211 non-null    int64
 289  t2p2_earnedgold               211 non-null    int64
 290  t2p2_earned gpm               211 non-null    float64
 291  t2p2_goldspent                211 non-null    float64
 292  t2p2_minionkills              211 non-null    float64
 293  t2p2_monsterkills             211 non-null    float64
 294  t2p2_monsterkillsownjungle    211 non-null    float64
 295  t2p2_monsterkillsenemyjungle  211 non-null    float64
 296  t2p2_cspm                     211 non-null    float64
 297  t2p2_goldat10                 210 non-null    float64
 298  t2p2pat10                     210 non-null    float64
 299  t2p2_csat10                   210 non-null    float64
 300  t2p2_goldat15                 210 non-null    float64
 301  t2p2pat15                     210 non-null    float64
 302  t2p2_csat15                   210 non-null    float64
 303  t2p3_position                 211 non-null    object
 304  t2p3_player                   211 non-null    object
 305  t2p3_team                     211 non-null    object
 306  t2p3_champion                 211 non-null    object
 307  t2p3_kills                    211 non-null    int64
 308  t2p3_deaths                   211 non-null    int64
 309  t2p3_assists                  211 non-null    int64
 310  t2p3_firstblood               211 non-null    float64
 311  t2p3_firstbloodkill           211 non-null    float64
 312  t2p3_firstbloodassist         211 non-null    float64
 313  t2p3_firstbloodvictim         211 non-null    float64
 314  t2p3_damagetochampions        211 non-null    float64
 315  t2p3_dpm                      211 non-null    float64
 316  t2p3_wardsplaced              211 non-null    float64
 317  t2p3_wpm                      211 non-null    float64
 318  t2p3_wardskilled              211 non-null    float64
 319  t2p3_wcpm                     211 non-null    float64
 320  t2p3_controlwardsbought       211 non-null    float64
 321  t2p3_visionscore              211 non-null    float64
 322  t2p3_vspm                     211 non-null    float64
 323  t2p3_totalgold                211 non-null    int64
 324  t2p3_earnedgold               211 non-null    int64
 325  t2p3_earned gpm               211 non-null    float64
 326  t2p3_goldspent                211 non-null    float64
 327  t2p3_minionkills              211 non-null    float64
 328  t2p3_monsterkills             211 non-null    float64
 329  t2p3_monsterkillsownjungle    211 non-null    float64
 330  t2p3_monsterkillsenemyjungle  211 non-null    float64
 331  t2p3_cspm                     211 non-null    float64

In [22]:
lec.describe()

,playoffs,game,patch,gamelength,t1_result,t1_firstblood,t1_firstdragon,t1_dragons,t1_elementaldrakes,t1_infernals,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
count,211.000000,211.000000,211.000000,211.000000,211.000000,211.000000,210.000000,211.000000,210.000000,210.000000,...,211.000000,211.000000,211.000000,211.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,0.146919,1.218009,10.079431,2015.649289,0.488152,0.530806,0.452381,2.227488,2.157143,0.552381,...,16.042654,9.113744,1.739336,7.666513,3195.042857,4493.219048,75.176190,5119.533333,7108.185714,120.904762
std,0.354867,0.689967,0.048469,327.868818,0.501048,0.500237,0.498917,1.402516,1.369200,0.776213,...,13.546853,8.384586,3.616538,1.142489,351.506917,408.915662,11.856091,610.794370,634.624237,17.594597
min,0.000000,1.000000,10.010000,1201.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.826900,2348.000000,2849.000000,37.000000,3722.000000,4440.000000,57.000000
25%,0.000000,1.000000,10.040000,1791.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,...,6.000000,3.000000,0.000000,6.991100,2949.750000,4289.500000,68.000000,4722.250000,6726.500000,112.000000
50%,0.000000,1.000000,10.060000,1975.000000,0.000000,1.000000,0.000000,2.000000,2.000000,0.000000,...,12.000000,7.000000,0.000000,7.649000,3177.500000,4530.500000,76.500000,5030.000000,7182.000000,123.000000
75%,0.000000,1.000000,10.130000,2170.000000,1.000000,1.000000,1.000000,3.000000,3.000000,1.000000,...,24.000000,14.000000,2.000000,8.399300,3352.250000,4774.500000,83.000000,5516.250000,7540.500000,131.750000
max,1.000000,5.000000,10.150000,3064.000000,1.000000,1.000000,1.000000,5.000000,4.000000,4.000000,...,74.000000,41.000000,30.000000,10.385700,4400.000000,5278.000000,107.000000,7595.000000,8551.000000,157.000000

In [23]:
lec.shape

(211, 408)

In [24]:
# Cardinalidad
for i in lec.select_dtypes(include=object):
    print(f"La cardinalidad de la variable {i} es {(lec[i].nunique()/lec.shape[0])*100:.2f}%")

La cardinalidad de la variable date es 100.00%
La cardinalidad de la variable gameId es 100.00%
La cardinalidad de la variable league es 0.47%
La cardinalidad de la variable split es 0.95%
La cardinalidad de la variable t1_playerid es 4.74%
La cardinalidad de la variable t1_ban1 es 18.96%
La cardinalidad de la variable t1_ban2 es 22.27%
La cardinalidad de la variable t1_ban3 es 22.27%
La cardinalidad de la variable t1_ban4 es 30.81%
La cardinalidad de la variable t1_ban5 es 31.28%
La cardinalidad de la variable t2_playerid es 4.74%
La cardinalidad de la variable t2_ban1 es 15.17%
La cardinalidad de la variable t2_ban2 es 18.01%
La cardinalidad de la variable t2_ban3 es 22.27%
La cardinalidad de la variable t2_ban4 es 30.81%
La cardinalidad de la variable t2_ban5 es 32.23%
La cardinalidad de la variable t1p1_position es 0.47%
La cardinalidad de la variable t1p1_player es 6.64%
La cardinalidad de la variable t1p1_team es 4.74%
La cardinalidad de la variable t1p1_champion es 10.90%
La cardinalidad de la variable t1p2_position es 0.47%
La cardinalidad de la variable t1p2_player es 7.11%
La cardinalidad de la variable t1p2_team es 4.74%
La cardinalidad de la variable t1p2_champion es 9.00%
La cardinalidad de la variable t1p3_position es 0.47%
La cardinalidad de la variable t1p3_player es 7.11%
La cardinalidad de la variable t1p3_team es 4.74%
La cardinalidad de la variable t1p3_champion es 17.54%
La cardinalidad de la variable t1p4_position es 0.47%
La cardinalidad de la variable t1p4_player es 5.69%
La cardinalidad de la variable t1p4_team es 4.74%
La cardinalidad de la variable t1p4_champion es 12.80%
La cardinalidad de la variable t1p5_position es 0.47%
La cardinalidad de la variable t1p5_player es 6.16%
La cardinalidad de la variable t1p5_team es 4.74%
La cardinalidad de la variable t1p5_champion es 17.54%
La cardinalidad de la variable t2p1_position es 0.47%
La cardinalidad de la variable t2p1_player es 6.64%
La cardinalidad de la variable t2p1_team es 4.74%
La cardinalidad de la variable t2p1_champion es 10.43%
La cardinalidad de la variable t2p2_position es 0.47%
La cardinalidad de la variable t2p2_player es 6.64%
La cardinalidad de la variable t2p2_team es 4.74%
La cardinalidad de la variable t2p2_champion es 9.48%
La cardinalidad de la variable t2p3_position es 0.47%
La cardinalidad de la variable t2p3_player es 7.11%
La cardinalidad de la variable t2p3_team es 4.74%
La cardinalidad de la variable t2p3_champion es 17.06%
La cardinalidad de la variable t2p4_position es 0.47%
La cardinalidad de la variable t2p4_player es 5.69%
La cardinalidad de la variable t2p4_team es 4.74%
La cardinalidad de la variable t2p4_champion es 10.43%
La cardinalidad de la variable t2p5_position es 0.47%
La cardinalidad de la variable t2p5_player es 6.16%
La cardinalidad de la variable t2p5_team es 4.74%
La cardinalidad de la variable t2p5_champion es 18.01%

#### LCS

In [25]:
lcs = S10_dataset[S10_dataset["league"] == "LCS"]

In [26]:
lcs.head()

,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,t1_ban1,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
72,2020-01-25 21:37:00,1270555,LCS,Spring,0,1,10.01,1474,Cloud9,Irelia,...,0.0,0.0,0.0,6.5943,3012.0,4420.0,76.0,4681.0,6176.0,102.0
73,2020-01-25 22:32:00,1270576,LCS,Spring,0,1,10.01,2413,Counter Logic Gaming,Irelia,...,9.0,0.0,1.0,6.5893,3230.0,4369.0,79.0,5197.0,7569.0,133.0
74,2020-01-25 23:39:00,1270592,LCS,Spring,0,1,10.01,2282,100 Thieves,Qiyana,...,16.0,12.0,0.0,6.4943,3331.0,5016.0,81.0,5196.0,7026.0,119.0
75,2020-01-26 00:44:00,1270607,LCS,Spring,0,1,10.01,2312,Immortals,Rumble,...,33.0,7.0,7.0,9.2907,3253.0,4106.0,69.0,5394.0,7319.0,134.0
81,2020-01-26 19:20:00,1270837,LCS,Spring,0,1,10.01,1687,Dignitas,Qiyana,...,17.0,8.0,0.0,7.1488,2973.0,4516.0,73.0,4592.0,6868.0,117.0

In [27]:
lcs.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 225 entries, 72 to 5099
Data columns (total 408 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    date                          225 non-null    object
 1    gameId                        225 non-null    object
 2    league                        225 non-null    object
 3    split                         225 non-null    object
 4    playoffs                      225 non-null    int64
 5    game                          225 non-null    int64
 6    patch                         225 non-null    float64
 7    gamelength                    225 non-null    int64
 8    t1_playerid                   225 non-null    object
 9    t1_ban1                       225 non-null    object
 10   t1_ban2                       225 non-null    object
 11   t1_ban3                       225 non-null    object
 12   t1_ban4                       225 non-null    object
 13   t1_ban5                       224 non-null    object
 14   t1_result                     225 non-null    int64
 15   t1_firstblood                 225 non-null    float64
 16   t1_firstdragon                225 non-null    float64
 17   t1_dragons                    225 non-null    int64
 18   t1_elementaldrakes            222 non-null    float64
 19   t1_infernals                  222 non-null    float64
 20   t1_mountains                  222 non-null    float64
 21   t1_clouds                     222 non-null    float64
 22   t1_oceans                     222 non-null    float64
 23   t1_elders                     225 non-null    float64
 24   t1_firstherald                225 non-null    float64
 25   t1_heralds                    225 non-null    float64
 26   t1_firstbaron                 225 non-null    float64
 27   t1_barons                     225 non-null    int64
 28   t1_firsttower                 225 non-null    float64
 29   t1_towers                     225 non-null    int64
 30   t1_firstmidtower              225 non-null    float64
 31   t1_firsttothreetowers         225 non-null    float64
 32   t1_inhibitors                 225 non-null    float64
 33   t2_playerid                   225 non-null    object
 34   t2_ban1                       225 non-null    object
 35   t2_ban2                       225 non-null    object
 36   t2_ban3                       225 non-null    object
 37   t2_ban4                       225 non-null    object
 38   t2_ban5                       225 non-null    object
 39   t2_result                     225 non-null    int64
 40   t2_firstblood                 225 non-null    float64
 41   t2_firstdragon                225 non-null    float64
 42   t2_dragons                    225 non-null    int64
 43   t2_elementaldrakes            222 non-null    float64
 44   t2_infernals                  222 non-null    float64
 45   t2_mountains                  222 non-null    float64
 46   t2_clouds                     222 non-null    float64
 47   t2_oceans                     222 non-null    float64
 48   t2_elders                     225 non-null    float64
 49   t2_firstherald                225 non-null    float64
 50   t2_heralds                    225 non-null    float64
 51   t2_firstbaron                 225 non-null    float64
 52   t2_barons                     225 non-null    int64
 53   t2_firsttower                 225 non-null    float64
 54   t2_towers                     225 non-null    int64
 55   t2_firstmidtower              225 non-null    float64
 56   t2_firsttothreetowers         225 non-null    float64
 57   t2_inhibitors                 225 non-null    float64
 58   t1p1_position                 225 non-null    object
 59   t1p1_player                   225 non-null    object
 60   t1p1_team                     225 non-null    object
 61   t1p1_champion                 225 non-null    object
 62   t1p1_kills                    225 non-null    int64
 63   t1p1_deaths                   225 non-null    int64
 64   t1p1_assists                  225 non-null    int64
 65   t1p1_firstblood               225 non-null    float64
 66   t1p1_firstbloodkill           225 non-null    float64
 67   t1p1_firstbloodassist         225 non-null    float64
 68   t1p1_firstbloodvictim         225 non-null    float64
 69   t1p1_damagetochampions        225 non-null    float64
 70   t1p1_dpm                      225 non-null    float64
 71   t1p1_wardsplaced              225 non-null    float64
 72   t1p1_wpm                      225 non-null    float64
 73   t1p1_wardskilled              225 non-null    float64
 74   t1p1_wcpm                     225 non-null    float64
 75   t1p1_controlwardsbought       225 non-null    float64
 76   t1p1_visionscore              225 non-null    float64
 77   t1p1_vspm                     225 non-null    float64
 78   t1p1_totalgold                225 non-null    int64
 79   t1p1_earnedgold               225 non-null    int64
 80   t1p1_earned gpm               225 non-null    float64
 81   t1p1_goldspent                225 non-null    float64
 82   t1p1_minionkills              225 non-null    float64
 83   t1p1_monsterkills             225 non-null    float64
 84   t1p1_monsterkillsownjungle    225 non-null    float64
 85   t1p1_monsterkillsenemyjungle  225 non-null    float64
 86   t1p1_cspm                     225 non-null    float64
 87   t1p1_goldat10                 225 non-null    float64
 88   t1p1pat10                     225 non-null    float64
 89   t1p1_csat10                   225 non-null    float64
 90   t1p1_goldat15                 225 non-null    float64
 91   t1p1pat15                     225 non-null    float64
 92   t1p1_csat15                   225 non-null    float64
 93   t1p2_position                 225 non-null    object
 94   t1p2_player                   225 non-null    object
 95   t1p2_team                     225 non-null    object
 96   t1p2_champion                 225 non-null    object
 97   t1p2_kills                    225 non-null    int64
 98   t1p2_deaths                   225 non-null    int64
 99   t1p2_assists                  225 non-null    int64
 100  t1p2_firstblood               225 non-null    float64
 101  t1p2_firstbloodkill           225 non-null    float64
 102  t1p2_firstbloodassist         225 non-null    float64
 103  t1p2_firstbloodvictim         225 non-null    float64
 104  t1p2_damagetochampions        225 non-null    float64
 105  t1p2_dpm                      225 non-null    float64
 106  t1p2_wardsplaced              225 non-null    float64
 107  t1p2_wpm                      225 non-null    float64
 108  t1p2_wardskilled              225 non-null    float64
 109  t1p2_wcpm                     225 non-null    float64
 110  t1p2_controlwardsbought       225 non-null    float64
 111  t1p2_visionscore              225 non-null    float64
 112  t1p2_vspm                     225 non-null    float64
 113  t1p2_totalgold                225 non-null    int64
 114  t1p2_earnedgold               225 non-null    int64
 115  t1p2_earned gpm               225 non-null    float64
 116  t1p2_goldspent                225 non-null    float64
 117  t1p2_minionkills              225 non-null    float64
 118  t1p2_monsterkills             225 non-null    float64
 119  t1p2_monsterkillsownjungle    225 non-null    float64
 120  t1p2_monsterkillsenemyjungle  225 non-null    float64
 121  t1p2_cspm                     225 non-null    float64
 122  t1p2_goldat10                 225 non-null    float64
 123  t1p2pat10                     225 non-null    float64
 124  t1p2_csat10                   225 non-null    float64
 125  t1p2_goldat15                 225 non-null    float64
 126  t1p2pat15                     225 non-null    float64
 127  t1p2_csat15                   225 non-null    float64
 128  t1p3_position                 225 non-null    object
 129  t1p3_player                   225 non-null    object
 130  t1p3_team                     225 non-null    object
 131  t1p3_champion                 225 non-null    object
 132  t1p3_kills                    225 non-null    int64
 133  t1p3_deaths                   225 non-null    int64
 134  t1p3_assists                  225 non-null    int64
 135  t1p3_firstblood               225 non-null    float64
 136  t1p3_firstbloodkill           225 non-null    float64
 137  t1p3_firstbloodassist         225 non-null    float64
 138  t1p3_firstbloodvictim         225 non-null    float64
 139  t1p3_damagetochampions        225 non-null    float64
 140  t1p3_dpm                      225 non-null    float64
 141  t1p3_wardsplaced              225 non-null    float64
 142  t1p3_wpm                      225 non-null    float64
 143  t1p3_wardskilled              225 non-null    float64
 144  t1p3_wcpm                     225 non-null    float64
 145  t1p3_controlwardsbought       225 non-null    float64
 146  t1p3_visionscore              225 non-null    float64
 147  t1p3_vspm                     225 non-null    float64
 148  t1p3_totalgold                225 non-null    int64
 149  t1p3_earnedgold               225 non-null    int64
 150  t1p3_earned gpm               225 non-null    float64
 151  t1p3_goldspent                225 non-null    float64
 152  t1p3_minionkills              225 non-null    float64
 153  t1p3_monsterkills             225 non-null    float64
 154  t1p3_monsterkillsownjungle    225 non-null    float64
 155  t1p3_monsterkillsenemyjungle  225 non-null    float64
 156  t1p3_cspm                     225 non-null    float64
 157  t1p3_goldat10                 225 non-null    float64
 158  t1p3pat10                     225 non-null    float64
 159  t1p3_csat10                   225 non-null    float64
 160  t1p3_goldat15                 225 non-null    float64
 161  t1p3pat15                     225 non-null    float64
 162  t1p3_csat15                   225 non-null    float64
 163  t1p4_position                 225 non-null    object
 164  t1p4_player                   225 non-null    object
 165  t1p4_team                     225 non-null    object
 166  t1p4_champion                 225 non-null    object
 167  t1p4_kills                    225 non-null    int64
 168  t1p4_deaths                   225 non-null    int64
 169  t1p4_assists                  225 non-null    int64
 170  t1p4_firstblood               225 non-null    float64
 171  t1p4_firstbloodkill           225 non-null    float64
 172  t1p4_firstbloodassist         225 non-null    float64
 173  t1p4_firstbloodvictim         225 non-null    float64
 174  t1p4_damagetochampions        225 non-null    float64
 175  t1p4_dpm                      225 non-null    float64
 176  t1p4_wardsplaced              225 non-null    float64
 177  t1p4_wpm                      225 non-null    float64
 178  t1p4_wardskilled              225 non-null    float64
 179  t1p4_wcpm                     225 non-null    float64
 180  t1p4_controlwardsbought       225 non-null    float64
 181  t1p4_visionscore              225 non-null    float64
 182  t1p4_vspm                     225 non-null    float64
 183  t1p4_totalgold                225 non-null    int64
 184  t1p4_earnedgold               225 non-null    int64
 185  t1p4_earned gpm               225 non-null    float64
 186  t1p4_goldspent                225 non-null    float64
 187  t1p4_minionkills              225 non-null    float64
 188  t1p4_monsterkills             225 non-null    float64
 189  t1p4_monsterkillsownjungle    225 non-null    float64
 190  t1p4_monsterkillsenemyjungle  225 non-null    float64
 191  t1p4_cspm                     225 non-null    float64
 192  t1p4_goldat10                 225 non-null    float64
 193  t1p4pat10                     225 non-null    float64
 194  t1p4_csat10                   225 non-null    float64
 195  t1p4_goldat15                 225 non-null    float64
 196  t1p4pat15                     225 non-null    float64
 197  t1p4_csat15                   225 non-null    float64
 198  t1p5_position                 225 non-null    object
 199  t1p5_player                   225 non-null    object
 200  t1p5_team                     225 non-null    object
 201  t1p5_champion                 225 non-null    object
 202  t1p5_kills                    225 non-null    int64
 203  t1p5_deaths                   225 non-null    int64
 204  t1p5_assists                  225 non-null    int64
 205  t1p5_firstblood               225 non-null    float64
 206  t1p5_firstbloodkill           225 non-null    float64
 207  t1p5_firstbloodassist         225 non-null    float64
 208  t1p5_firstbloodvictim         225 non-null    float64
 209  t1p5_damagetochampions        225 non-null    float64
 210  t1p5_dpm                      225 non-null    float64
 211  t1p5_wardsplaced              225 non-null    float64
 212  t1p5_wpm                      225 non-null    float64
 213  t1p5_wardskilled              225 non-null    float64
 214  t1p5_wcpm                     225 non-null    float64
 215  t1p5_controlwardsbought       225 non-null    float64
 216  t1p5_visionscore              225 non-null    float64
 217  t1p5_vspm                     225 non-null    float64
 218  t1p5_totalgold                225 non-null    int64
 219  t1p5_earnedgold               225 non-null    int64
 220  t1p5_earned gpm               225 non-null    float64
 221  t1p5_goldspent                225 non-null    float64
 222  t1p5_minionkills              225 non-null    float64
 223  t1p5_monsterkills             225 non-null    float64
 224  t1p5_monsterkillsownjungle    225 non-null    float64
 225  t1p5_monsterkillsenemyjungle  225 non-null    float64
 226  t1p5_cspm                     225 non-null    float64
 227  t1p5_goldat10                 225 non-null    float64
 228  t1p5pat10                     225 non-null    float64
 229  t1p5_csat10                   225 non-null    float64
 230  t1p5_goldat15                 225 non-null    float64
 231  t1p5pat15                     225 non-null    float64
 232  t1p5_csat15                   225 non-null    float64
 233  t2p1_position                 225 non-null    object
 234  t2p1_player                   225 non-null    object
 235  t2p1_team                     225 non-null    object
 236  t2p1_champion                 225 non-null    object
 237  t2p1_kills                    225 non-null    int64
 238  t2p1_deaths                   225 non-null    int64
 239  t2p1_assists                  225 non-null    int64
 240  t2p1_firstblood               225 non-null    float64
 241  t2p1_firstbloodkill           225 non-null    float64
 242  t2p1_firstbloodassist         225 non-null    float64
 243  t2p1_firstbloodvictim         225 non-null    float64
 244  t2p1_damagetochampions        225 non-null    float64
 245  t2p1_dpm                      225 non-null    float64
 246  t2p1_wardsplaced              225 non-null    float64
 247  t2p1_wpm                      225 non-null    float64
 248  t2p1_wardskilled              225 non-null    float64
 249  t2p1_wcpm                     225 non-null    float64
 250  t2p1_controlwardsbought       225 non-null    float64
 251  t2p1_visionscore              225 non-null    float64
 252  t2p1_vspm                     225 non-null    float64
 253  t2p1_totalgold                225 non-null    int64
 254  t2p1_earnedgold               225 non-null    int64
 255  t2p1_earned gpm               225 non-null    float64
 256  t2p1_goldspent                225 non-null    float64
 257  t2p1_minionkills              225 non-null    float64
 258  t2p1_monsterkills             225 non-null    float64
 259  t2p1_monsterkillsownjungle    225 non-null    float64
 260  t2p1_monsterkillsenemyjungle  225 non-null    float64
 261  t2p1_cspm                     225 non-null    float64
 262  t2p1_goldat10                 225 non-null    float64
 263  t2p1pat10                     225 non-null    float64
 264  t2p1_csat10                   225 non-null    float64
 265  t2p1_goldat15                 225 non-null    float64
 266  t2p1pat15                     225 non-null    float64
 267  t2p1_csat15                   225 non-null    float64
 268  t2p2_position                 225 non-null    object
 269  t2p2_player                   225 non-null    object
 270  t2p2_team                     225 non-null    object
 271  t2p2_champion                 225 non-null    object
 272  t2p2_kills                    225 non-null    int64
 273  t2p2_deaths                   225 non-null    int64
 274  t2p2_assists                  225 non-null    int64
 275  t2p2_firstblood               225 non-null    float64
 276  t2p2_firstbloodkill           225 non-null    float64
 277  t2p2_firstbloodassist         225 non-null    float64
 278  t2p2_firstbloodvictim         225 non-null    float64
 279  t2p2_damagetochampions        225 non-null    float64
 280  t2p2_dpm                      225 non-null    float64
 281  t2p2_wardsplaced              225 non-null    float64
 282  t2p2_wpm                      225 non-null    float64
 283  t2p2_wardskilled              225 non-null    float64
 284  t2p2_wcpm                     225 non-null    float64
 285  t2p2_controlwardsbought       225 non-null    float64
 286  t2p2_visionscore              225 non-null    float64
 287  t2p2_vspm                     225 non-null    float64
 288  t2p2_totalgold                225 non-null    int64
 289  t2p2_earnedgold               225 non-null    int64
 290  t2p2_earned gpm               225 non-null    float64
 291  t2p2_goldspent                225 non-null    float64
 292  t2p2_minionkills              225 non-null    float64
 293  t2p2_monsterkills             225 non-null    float64
 294  t2p2_monsterkillsownjungle    225 non-null    float64
 295  t2p2_monsterkillsenemyjungle  225 non-null    float64
 296  t2p2_cspm                     225 non-null    float64
 297  t2p2_goldat10                 225 non-null    float64
 298  t2p2pat10                     225 non-null    float64
 299  t2p2_csat10                   225 non-null    float64
 300  t2p2_goldat15                 225 non-null    float64
 301  t2p2pat15                     225 non-null    float64
 302  t2p2_csat15                   225 non-null    float64
 303  t2p3_position                 225 non-null    object
 304  t2p3_player                   225 non-null    object
 305  t2p3_team                     225 non-null    object
 306  t2p3_champion                 225 non-null    object
 307  t2p3_kills                    225 non-null    int64
 308  t2p3_deaths                   225 non-null    int64
 309  t2p3_assists                  225 non-null    int64
 310  t2p3_firstblood               225 non-null    float64
 311  t2p3_firstbloodkill           225 non-null    float64
 312  t2p3_firstbloodassist         225 non-null    float64
 313  t2p3_firstbloodvictim         225 non-null    float64
 314  t2p3_damagetochampions        225 non-null    float64
 315  t2p3_dpm                      225 non-null    float64
 316  t2p3_wardsplaced              225 non-null    float64
 317  t2p3_wpm                      225 non-null    float64
 318  t2p3_wardskilled              225 non-null    float64
 319  t2p3_wcpm                     225 non-null    float64
 320  t2p3_controlwardsbought       225 non-null    float64
 321  t2p3_visionscore              225 non-null    float64
 322  t2p3_vspm                     225 non-null    float64
 323  t2p3_totalgold                225 non-null    int64
 324  t2p3_earnedgold               225 non-null    int64
 325  t2p3_earned gpm               225 non-null    float64
 326  t2p3_goldspent                225 non-null    float64
 327  t2p3_minionkills              225 non-null    float64
 328  t2p3_monsterkills             225 non-null    float64
 329  t2p3_monsterkillsownjungle    225 non-null    float64
 330  t2p3_monsterkillsenemyjungle  225 non-null    float64
 331  t2p3_cspm                     225 non-null    float64

In [28]:
lcs.describe()

,playoffs,game,patch,gamelength,t1_result,t1_firstblood,t1_firstdragon,t1_dragons,t1_elementaldrakes,t1_infernals,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
count,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,222.000000,222.000000,...,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000,225.000000
mean,0.191111,1.284444,10.082844,2042.888889,0.577778,0.524444,0.471111,2.706667,2.585586,0.626126,...,13.004444,6.288889,1.902222,7.701349,3201.586667,4525.617778,74.755556,5052.595556,7132.315556,119.924444
std,0.394053,0.789992,0.049937,390.127167,0.495015,0.500516,0.500278,1.467870,1.368478,0.866596,...,11.001014,6.507627,3.346006,1.068844,311.826650,372.017059,10.220680,608.818111,590.374369,15.526147
min,0.000000,1.000000,10.010000,1337.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.441500,2564.000000,3268.000000,30.000000,3750.000000,4480.000000,50.000000
25%,0.000000,1.000000,10.040000,1779.000000,0.000000,0.000000,0.000000,2.000000,1.250000,0.000000,...,4.000000,1.000000,0.000000,6.975700,2986.000000,4310.000000,68.000000,4652.000000,6807.000000,113.000000
50%,0.000000,1.000000,10.060000,1963.000000,1.000000,1.000000,0.000000,3.000000,3.000000,0.000000,...,10.000000,4.000000,0.000000,7.700800,3167.000000,4563.000000,76.000000,4952.000000,7161.000000,121.000000
75%,0.000000,1.000000,10.130000,2286.000000,1.000000,1.000000,1.000000,4.000000,4.000000,1.000000,...,20.000000,9.000000,3.000000,8.408100,3398.000000,4803.000000,82.000000,5409.000000,7504.000000,130.000000
max,1.000000,5.000000,10.160000,3680.000000,1.000000,1.000000,1.000000,6.000000,4.000000,4.000000,...,56.000000,47.000000,14.000000,10.835600,4485.000000,5355.000000,96.000000,7401.000000,8728.000000,157.000000

In [29]:
lcs.shape

(225, 408)

In [30]:
# Cardinalidad
for i in lcs.select_dtypes(include=object):
    print(f"La cardinalidad de la variable {i} es {(lcs[i].nunique()/lcs.shape[0])*100:.2f}%")

La cardinalidad de la variable date es 100.00%
La cardinalidad de la variable gameId es 100.00%
La cardinalidad de la variable league es 0.44%
La cardinalidad de la variable split es 0.89%
La cardinalidad de la variable t1_playerid es 4.44%
La cardinalidad de la variable t1_ban1 es 17.33%
La cardinalidad de la variable t1_ban2 es 20.89%
La cardinalidad de la variable t1_ban3 es 23.11%
La cardinalidad de la variable t1_ban4 es 29.78%
La cardinalidad de la variable t1_ban5 es 30.67%
La cardinalidad de la variable t2_playerid es 4.44%
La cardinalidad de la variable t2_ban1 es 13.33%
La cardinalidad de la variable t2_ban2 es 20.00%
La cardinalidad de la variable t2_ban3 es 24.44%
La cardinalidad de la variable t2_ban4 es 26.22%
La cardinalidad de la variable t2_ban5 es 26.22%
La cardinalidad de la variable t1p1_position es 0.44%
La cardinalidad de la variable t1p1_player es 6.22%
La cardinalidad de la variable t1p1_team es 4.44%
La cardinalidad de la variable t1p1_champion es 10.22%
La cardinalidad de la variable t1p2_position es 0.44%
La cardinalidad de la variable t1p2_player es 6.22%
La cardinalidad de la variable t1p2_team es 4.44%
La cardinalidad de la variable t1p2_champion es 7.56%
La cardinalidad de la variable t1p3_position es 0.44%
La cardinalidad de la variable t1p3_player es 6.67%
La cardinalidad de la variable t1p3_team es 4.44%
La cardinalidad de la variable t1p3_champion es 13.78%
La cardinalidad de la variable t1p4_position es 0.44%
La cardinalidad de la variable t1p4_player es 7.11%
La cardinalidad de la variable t1p4_team es 4.44%
La cardinalidad de la variable t1p4_champion es 8.89%
La cardinalidad de la variable t1p5_position es 0.44%
La cardinalidad de la variable t1p5_player es 6.22%
La cardinalidad de la variable t1p5_team es 4.44%
La cardinalidad de la variable t1p5_champion es 12.44%
La cardinalidad de la variable t2p1_position es 0.44%
La cardinalidad de la variable t2p1_player es 6.22%
La cardinalidad de la variable t2p1_team es 4.44%
La cardinalidad de la variable t2p1_champion es 9.78%
La cardinalidad de la variable t2p2_position es 0.44%
La cardinalidad de la variable t2p2_player es 6.22%
La cardinalidad de la variable t2p2_team es 4.44%
La cardinalidad de la variable t2p2_champion es 7.11%
La cardinalidad de la variable t2p3_position es 0.44%
La cardinalidad de la variable t2p3_player es 6.22%
La cardinalidad de la variable t2p3_team es 4.44%
La cardinalidad de la variable t2p3_champion es 18.22%
La cardinalidad de la variable t2p4_position es 0.44%
La cardinalidad de la variable t2p4_player es 6.67%
La cardinalidad de la variable t2p4_team es 4.44%
La cardinalidad de la variable t2p4_champion es 8.00%
La cardinalidad de la variable t2p5_position es 0.44%
La cardinalidad de la variable t2p5_player es 6.22%
La cardinalidad de la variable t2p5_team es 4.44%
La cardinalidad de la variable t2p5_champion es 14.67%

### Por Regiones

#### Asia

In [45]:
asia = pd.concat([lck, lpl])
asia

,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,t1_ban1,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
184,2020-02-05 06:34:00,1302595,LCK,Spring,0,1,10.02,2441,T1,Syndra,...,42.0,25.0,4.0,7.9394,3541.0,4810.0,81.0,5188.0,7068.0,126.0
185,2020-02-05 09:00:00,1302628,LCK,Spring,0,2,10.02,2870,DAMWON Gaming,Rek'Sai,...,32.0,24.0,4.0,7.9024,3477.0,4650.0,75.0,5558.0,8287.0,128.0
186,2020-02-05 10:14:00,1302635,LCK,Spring,0,3,10.02,2837,T1,Mordekaiser,...,56.0,27.0,15.0,10.1727,2997.0,4417.0,73.0,4730.0,7102.0,123.0
187,2020-02-05 11:33:00,1302651,LCK,Spring,0,1,10.02,1748,KT Rolster,Irelia,...,9.0,9.0,0.0,7.7231,3032.0,4370.0,77.0,4717.0,7416.0,129.0
188,2020-02-05 13:10:00,1292960,LCK,Spring,0,2,10.02,1609,Gen.G,Olaf,...,13.0,12.0,1.0,7.8682,3021.0,4535.0,73.0,4907.0,7626.0,127.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5014,2020-08-15 11:04:00,6682-8838,LPL,Summer,1,3,10.16,2080,Victory Five,Caitlyn,...,13.0,11.0,0.0,7.0962,3338.0,4926.0,83.0,5917.0,7252.0,125.0
5021,2020-08-15 11:58:00,6682-8839,LPL,Summer,1,4,10.16,1350,Suning,Sett,...,24.0,20.0,0.0,8.4444,2757.0,3659.0,65.0,4600.0,6274.0,121.0
5065,2020-08-16 09:18:00,6683-8851,LPL,Summer,1,1,10.16,1472,Invictus Gaming,Renekton,...,20.0,13.0,4.0,8.1522,3014.0,4488.0,67.0,5377.0,7263.0,107.0
5070,2020-08-16 10:00:00,6683-8852,LPL,Summer,1,2,10.16,1433,Invictus Gaming,Renekton,...,4.0,3.0,0.0,7.3273,2976.0,4430.0,76.0,4524.0,6784.0,113.0
5074,2020-08-16 10:42:00,6683-8854,LPL,Summer,1,3,10.16,1580,LGD Gaming,Orianna,...,7.0,5.0,1.0,9.4557,2976.0,4430.0,76.0,4524.0,6784.0,113.0

#### Occidente

In [44]:
occidente = pd.concat([lec, lcs])
occidente

,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,t1_ban1,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
53,2020-01-24 16:17:00,1390161,LEC,Spring,0,1,10.01,2059,G2 Esports,Irelia,...,1.0,1.0,0.0,6.7606,3143.0,4814.0,69.0,5538.0,8084.0,126.0
54,2020-01-24 17:40:00,1390170,LEC,Spring,0,1,10.01,3049,SK Gaming,Lucian,...,22.0,15.0,0.0,6.7891,3218.0,4630.0,84.0,4794.0,7290.0,129.0
55,2020-01-24 19:00:00,1390196,LEC,Spring,0,1,10.01,2544,Rogue,Rumble,...,32.0,32.0,0.0,8.2075,2837.0,4224.0,63.0,4677.0,6490.0,110.0
56,2020-01-24 20:11:00,1390202,LEC,Spring,0,1,10.01,2392,Excel Esports,Thresh,...,9.0,4.0,1.0,6.2709,3665.0,5044.0,90.0,5870.0,8125.0,145.0
57,2020-01-24 21:18:00,1390213,LEC,Spring,0,1,10.01,2554,Fnatic,Lucian,...,23.0,20.0,3.0,8.1049,3175.0,4603.0,77.0,5024.0,7266.0,127.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5044,2020-08-15 20:43:00,1430953,LCS,Summer,1,2,10.16,1868,Dignitas,LeBlanc,...,8.0,8.0,0.0,6.1991,3511.0,4579.0,85.0,4869.0,6486.0,121.0
5046,2020-08-15 21:37:00,1430955,LCS,Summer,1,3,10.16,1685,Team SoloMid,Azir,...,3.0,2.0,0.0,6.9436,2929.0,4434.0,68.0,4556.0,7504.0,116.0
5096,2020-08-16 19:30:00,1441095,LCS,Summer,1,1,10.16,1938,Evil Geniuses,Olaf,...,10.0,6.0,0.0,8.9783,3459.0,5141.0,89.0,6400.0,8165.0,147.0
5098,2020-08-16 20:35:00,1441104,LCS,Summer,1,2,10.16,2862,100 Thieves,Sett,...,56.0,47.0,1.0,7.2327,2692.0,3908.0,57.0,4316.0,5285.0,74.0
5099,2020-08-16 21:47:00,1441108,LCS,Summer,1,3,10.16,1443,Evil Geniuses,Olaf,...,6.0,4.0,0.0,7.2765,3034.0,4457.0,60.0,4913.0,6973.0,105.0

### Ligas mayoritarias

In [46]:
major_leagues = pd.concat([asia, occidente])
major_leagues

,date,gameId,league,split,playoffs,game,patch,gamelength,t1_playerid,t1_ban1,...,t2p5_monsterkills,t2p5_monsterkillsownjungle,t2p5_monsterkillsenemyjungle,t2p5_cspm,t2p5_goldat10,t2p5pat10,t2p5_csat10,t2p5_goldat15,t2p5pat15,t2p5_csat15
184,2020-02-05 06:34:00,1302595,LCK,Spring,0,1,10.02,2441,T1,Syndra,...,42.0,25.0,4.0,7.9394,3541.0,4810.0,81.0,5188.0,7068.0,126.0
185,2020-02-05 09:00:00,1302628,LCK,Spring,0,2,10.02,2870,DAMWON Gaming,Rek'Sai,...,32.0,24.0,4.0,7.9024,3477.0,4650.0,75.0,5558.0,8287.0,128.0
186,2020-02-05 10:14:00,1302635,LCK,Spring,0,3,10.02,2837,T1,Mordekaiser,...,56.0,27.0,15.0,10.1727,2997.0,4417.0,73.0,4730.0,7102.0,123.0
187,2020-02-05 11:33:00,1302651,LCK,Spring,0,1,10.02,1748,KT Rolster,Irelia,...,9.0,9.0,0.0,7.7231,3032.0,4370.0,77.0,4717.0,7416.0,129.0
188,2020-02-05 13:10:00,1292960,LCK,Spring,0,2,10.02,1609,Gen.G,Olaf,...,13.0,12.0,1.0,7.8682,3021.0,4535.0,73.0,4907.0,7626.0,127.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5044,2020-08-15 20:43:00,1430953,LCS,Summer,1,2,10.16,1868,Dignitas,LeBlanc,...,8.0,8.0,0.0,6.1991,3511.0,4579.0,85.0,4869.0,6486.0,121.0
5046,2020-08-15 21:37:00,1430955,LCS,Summer,1,3,10.16,1685,Team SoloMid,Azir,...,3.0,2.0,0.0,6.9436,2929.0,4434.0,68.0,4556.0,7504.0,116.0
5096,2020-08-16 19:30:00,1441095,LCS,Summer,1,1,10.16,1938,Evil Geniuses,Olaf,...,10.0,6.0,0.0,8.9783,3459.0,5141.0,89.0,6400.0,8165.0,147.0
5098,2020-08-16 20:35:00,1441104,LCS,Summer,1,2,10.16,2862,100 Thieves,Sett,...,56.0,47.0,1.0,7.2327,2692.0,3908.0,57.0,4316.0,5285.0,74.0
5099,2020-08-16 21:47:00,1441108,LCS,Summer,1,3,10.16,1443,Evil Geniuses,Olaf,...,6.0,4.0,0.0,7.2765,3034.0,4457.0,60.0,4913.0,6973.0,105.0